0xfe/vexflow

- src/gracenote.js
Fixes #280 : Grace note slashes don't render in SVG or Raphael.
Replaces first lineTo() call with moveTo() to correctly set the pen.
> moveTo before lineTo in gracenote.js slashes

- src/keysignature.js
- tests/key_clef_tests.js
Fixes #295 
Previously, key signatures only rendered on the correct lines in treble, alto, tenor, and bass clefs. This PR provides support for key signatures in all of the clefs supported by VexFlow (treble, soprano, mezzo-soprano, alto, tenor, baritone-f, baritone-c, bass, french, subbass, percussion).
Previously, for instance, mezzo-soprano would show flats on the wrong lines/spaces:
This, and others, have been corrected:
With testing revised for all keys in all clefs.
> All clefs keys

- src/clefnote.js
- src/stave.js
Small problem I ran into when I tried to draw something on a new context. The glyphs associated with staves and clefnotes never got the setContext message passed to them since they already had a context. This fixes the problem by having stave and clefnote set their glyph's context as part of their setContext function.
> adds context to glyphs for clefnote and stave glyphs

- src/beam.js
- tests/auto_beam_formatting_tests.js
This change allows beam slope calculations to be bypassed in the beam generation logic, and allows for a flat beam.  The current, default behavior of generateBeams() is unchanged.
The offset for the flat beam can be universally applied for all of the notes sent to generateBeams(), or it can be automatically calculated per beam group.
To enable flat beams with different heights per beam group, send in `flat_beams: true` to the generateBeams() options.
If the same height is desired for all of the beams in the set of notes sent to generateBeams(), a 2nd parameter, `flat_beam_offset`, can be passed along with `flat_beams: true`.  This parameter is ignored if `flat_beams` is `false` (the default).
I added 5 tests for the 2 modes described above with both up-stems and down-stems (and mixed, up …
> Enable Flat beams in Beam.generateBeams()

- src/stavenote.js
Fixes #346 -- two-lines of code erroneously placed in a for-loop caused an extra half-staff-line of space to be added to `getBoundingBox().height` for every note after the first in a `StaveNote` in stemless rhythms (whole notes & breves).
This PR addresses & corrects that:
> fix(stavenote.js): getBoundingBox should not add extra height to chords

- package.json
- src/boundingboxcomputation.js
- src/glyph.js
- src/keysignature.js
This is a WIP.
Note that this is one of the changes outlined in https://github.com/0xfe/vexflow/issues/349
* Add a `BoundingBoxComputation` class -- [which was completely taken from here](https://github.com/icons8/svg-path-bounding-box/blob/master/lib/Path/BoundingBox.js)
* This is only needed for a temporary amount of time. With SMuFL metadata we would no longer need a utilitiy to determine glyph bounding boxes.
* Add static method `Glyph.getOutlineBoundingBox`
* Did a bit of refactoring to share logic between this and `Glyph.renderOutline`
* Every time `glyph.reset()` is called, the `bbox` property is set
* `Glyph.getMetrics()` will now return the `width` and `height` of the `bbox`
* Removed `Glyph.setWidth()` since there should be no reason to manually set the width of a glyph
* This …
> Accurate glyph metrics using a Glyph's Bounding Box

- src/glyphs.html
- src/index.js
The file glyphs.html uses `Vex.Flow.Font` to display the glyphs, but that object was no longer being exposed after the ES6 rewrite. Fixed this by adding `Vex.Flow.Font` to index.js.
> Expose Vex.Flow.Font to fix glyphs.html

- .eslintrc.json
- src/beam.js
- src/formatter.js
- src/notehead.js
- src/stavenote.js
- src/stem.js
- src/stemmablenote.js
- src/tables.js
- src/tabnote.js
- tests/stavenote_tests.js
- tests/vexflow_test_helpers.js
Still  a WIP, tab is broken.
Important things to note:
* The logic `StaveNote.getStemExtents()` has been removed and now delegates to `Stem.getExtents()`
* Went through `Beam` and did a lot of renaming, most variable names were really vague and I think it's a lot easier to understand now.
* A lot of logic in `beam.applyStemExtensions` was just plain wrong mainly due to incorrect assumptions around stem coordinates because it's a [very confusing part of the codebase](https://github.com/0xfe/vexflow/wiki/Development-Gotchas) -- that method has been greatly simplified
* `Formatter.FormatAndDraw` now passes `options.stave` to `formatter.formatToStave` which is required to trigger the `postFormat`  lifecycle (this also explains why the stem extents were wrong in the articulation PR)
> Refactor stems/beams

- .eslintrc.json
- Gruntfile.js
- package.json
- src/.babelrc
Throwing this out there... I was unable to get fast incremental rebuilds working with rollup (@aaronmars do you know how?). If it's possible I'm happy to stick with it. But I couldn't figure it out, so I replaced rollup with webpack (using `grunt-webpack`).
See the rebuilds in action by running: `grunt webpack:watch`. On my machine, the initial build takes `~8s`, and a rebuild takes `~800ms`. Makes for a much nicer dev experience.
The `watch:scripts` task has been removed in favor of `webpack:watch` (in order to take advantage of webpack's built-in file watching). The task for building _without_ watching is `webpack:build`.
> Remove rollup in favor of webpack for super-fast incremental rebuilds. 

- tests/tuplet_tests.js
I had forgotten to pass down the `ratioed` option.
> Fix ratioed tuplet tests

- src/easyscore.js
> Fix missing easy score accidentals

- .gitignore
This is helpful because I often bypass the building process by creating a symlink from build/ to releases/ and it is best if git ignores a symlink (which is a file) just like it ignores a directory.
> Ignore both "build" and "build/"

- src/easyscore.js
- tests/easyscore_tests.js
Added support for all accidentals in the EasyScore syntax.
Actually, the original EasyScore regex for accidentals is broken https://github.com/0xfe/vexflow/blob/master/src/easyscore.js#L133: the regex `[b#n]+` means that accidentals such as `####` and `b##bnnn` would be allowed. This is also fixed in my PR.
> EasyScore accidentals

- src/boundingbox.js
- tests/boundingbox_tests.js
Hi Mohit,
I found a bug which is very simple but obvious, so I fixed and here is the PR.
Current BoundingBox mergeWith function was not working properly for some cases;
Box1 contains Box2 -> error calculating new_w or new_h
Thanks!
Taehoon
> Fix BoundingBox mergeWith function

- src/vex.js
ES6 rest parameter (`...args` in this case) returns a true array, not an "arguments" object, so no need for this indirection
> Removed unnecessary Array.prototype.slice() call

- src/factory.js
- src/modifier.js
- src/textbracket.js
- tests/textbracket_tests.js
Note the destructured `TextBracket` constructor parameters. I'm personally very fond of this pattern (I use it extensively with my React projects since all React components take a single `props` object). Makes default values really convenient without cluttering up the assignments in the body.
> Add TextBracket to Factory; refactor TextBracket tests

- src/factory.js
- tests/stavetie_tests.js
- tests/vexflow_test_helpers.js
~So I really got a little more experimental... but I think this managed to reduce boilerplate really clearly and isolates the parts being tested.~
~I've always found the string+test mapping in each `Start` function to be pretty annoying. So I got rid of it and rely on iteration through the keys using a `runModule` test helper.~
~Definitely looking for feedback on this!~
Also bug https://github.com/0xfe/vexflow/issues/489 was found during the course of this refactor.
> Refactor StaveTie tests

- tests/strokes_tests.js
On the last test, there are two formatting iterations: with and without justification. Testing justification is already done in the formatter tests, so I've only kept the the justified iteration.
> Refactor Stroke tests

- src/stavenote.js
- tests/threevoice_tests.js
Take a look at the diffs. They are significant due to the new test setup affecting the automatic rest alignment.
Some of these tests relied on formatting code that was executed *only if* missing a stave (which really doesn't make sense to me why any kind of multi-voice formatting would be attempted in this case). Anyway, we are soon making this an invalid state. So now, the rests are formatted by code that formats StaveNotes with a stave. But the output is not good. The vertical adjustments will have to be completely rewritten to take real bounding box metrics into account (but this can only happen once the new stave requirement is in place), and changes will need to be made to support >2 voices.
See comment in code for more details.
> Reset noteheads when `StaveNote#setKeyLine` is called; Refactor threevoice_tests.js;

- src/renderer.js
Use `window.devicePixelRatio` when setting up canvas
> Fix blurry canvas rendering on retina screens

- package.json
Fresh npm installs were pulling Webpack 3.0 — but 1.x is required for
the rest of the dependencies. This commit fixes that.
babel-loader requires babel-core to be installed locally or globally.
The missing dependency is added here.
> build(package.json): add webpack version, add babel-core dependency

- .eslintrc.json
- Gruntfile.js
- src/raphaelcontext.js
- tests/.eslintrc.json
- tests/accidental_tests.js
- tests/articulation_tests.js
- tests/bend_tests.js
- tests/ornament_tests.js
- tests/vexflow_test_helpers.js
- tests/vibrato_tests.js
[See rule documentation for details](http://eslint.org/docs/rules/dot-location). This now enforces the dot operator to be placed the same line as the property being accessed. All lingering occurrences of this style have now been fixed.
> Lint tests; Enable dot-location eslint rule;

- src/beam.js
- src/element.js
- src/glyph.js
- src/notehead.js
- src/stavenote.js
- src/stem.js
- tests/stavenote_tests.js
This PR consolidates various setStyle & applyStyle methods into the Element class, extends styling to glyphs and beams, and adds styling options on StaveNotes for stems, flags, and ledger lines.
Fixes #557
> Styling via Element

- src/element.js
- src/notehead.js
- src/stave.js
- src/stavenote.js
- tests/stavenote_tests.js
Fixes #566, fixes ledger line formatting issues remaining in #557.
Changes:
- Ledger line drawing is now handled entirely by `StaveNote`
- All ledger line logic is removed from `NoteHead`
- Ledger lines are now drawn with the same style of the staff they're related to
- If both displaced and non-displaced notes are present above or below the staff, ledger lines are drawn for both positions until no longer needed in either position.
- `Stave.setStyle()` is now available to match the api's of other `Element`s.
- `StaveNote.setLedgerLineStyle()` uses `Stave.getStyle()` as its default style, merging onto it any changes.
This results in two obvious visual changes throughout with ledger lines:
- Ledger lines are now thinner than before (1px, matching Vex.Flow.STAVE_LINE_THICKNESS)
- Ledger …
> Ledger Line Logic

- src/stavenote.js
- src/stem.js
Fixes an issue where calling `staveNote.setStyle(styleObject)` applied that style to all future elements drawn.
> fix(Stem & StaveNote): applyStyle called without restoreStyle in draw()

- src/dot.js
Resolves an issue preventing correct dot placement for rests.
> fix(dot.js): Dot.format should not overwrite dot.dot_shiftY. Fixes #607

- .editorconfig
Addressed #376 and added the .editorconfig. As you're extending airbnb as a base for eslint, I used their base editorconfig with an additional line so trailing whitespace isn't trimmed in .md files. The rest is standard.
```
root = true
[*]
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
end_of_line = lf
max_line_length = null
[*.md]
trim_trailing_whitespace = false
> Issue #376 - add .editorconfig

- src/music.js
ESLint Error: Unexpected template string expression on Line 231. Looks like template literals were intended instead of quotation marks.
Picked this one up when using Vexflow within create-react-app
> Fixed ESLint error

- src/gracenotegroup.js
- src/ornament.js
Hi,
we had some problems in opensheetmusicdisplay/opensheetmusicdisplay#293 that grace notes shifted to the right everytime we redraw stuff. We do this a lot because we can zoom in and out and also add debugging layers on top. Anyways I found that the GraceNoteGroup does this ```alignGraceNotesWithNote``` everytime it draws, thus adding the offset again and again which causes the whole group to shift.
My fix checks if the group is already aligned and skips that. It's rather quick and dirty (adding a prop after creation) but so is the mentioned function. Why is there formatting done during draw anyways?
> Fixed gracenote offset after redraw

- src/dot.js
Before this fix, dotted note dots get y-shifted a half line each render/draw:
We redraw a lot in OSMD compared to Vexflow tests, so we noticed [this issue](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/300) pretty quickly.
The bug was introduced by [fixing quarter dotted rest dot positioning](https://github.com/0xfe/vexflow/commit/298cd8813e0a545c31fb312bd9f7dfa31e634e17) ([#607](https://github.com/0xfe/vexflow/issues/607)).
Rest note and stave note shiftY seem to be handled differently, stave notes remember previous y-shift.
The dot_shiftY could also be refactored to operate the same for stave notes and rests (= vs +=), but this fix handles the difference.
All visual regression tests pass and i haven't noticed other issues, using this for a while in OSMD.
Dotted …
> Fix dotted note dot y-shifting each draw

- src/gracenotegroup.js
- src/modifier.js
- src/notesubgroup.js
- src/tickcontext.js
- tests/gracenote_tests.js
- tests/notesubgroup_tests.js
- tests/ornament_tests.js
Before, NoteSubGroup x-offset was reapplied every render, similar to what was mentioned in #632:
```tick_context.setX(x + x_offset);```
This resulted in NoteSubGroups moving x-wise every draw():
I improved and reapplied the fix from #632. Now, GraceNoteGroups and NoteSubGroups use the same align function in modifier.js, whereas before they both had an align function that was duplicate code. I tried moving the alignment to a format method, because it should rather be there than in draw(), but when i tried it seemed like it was too early and didn't work.
In TickContext I added the possibility to represent x-positioning as base x plus offset, so we can simply overwrite the x-offset and not apply the x-offset of the previous draw()-call to the next one.
This could be a good method to use in …
> fix NoteSubGroup x-shift each render

- src/tables.js
Hoping that this will be a useful contribution for an eventual push to allow for the complete SMuFL font plug in, letting a smooth transition from Gonville to SMuFL font plugin take place.  Gives a mapping for almost all glyphs from SMuFL names to Vexflow codepoints so that these can start being replaced in the hardcoded code and then eventually using the existing .json files, other SMuFL fonts could be used for an extended character set.
This pull request only contains the mappings for SMuFL to Gonville.  Next possible steps include allowing any glyph to be accessed in places such as TextNote and lyric annotations using the SMuFL name.  Then replacing references to codepoints to SMuFL names, and then creating plugable fonts.
A step towards #349 and esp. #350 ("SMuFL glyph name (eg: …
> SMuFL mappings in tables

- src/stavenote.js
- src/stem.js
- src/tables.js
Added code to allow the stem to connect to the custom note head at the expected place.
`stem_up_y_offset` and `stem_down_y_offset` are both needed because the stem meets at the bottom of the note head for some, and bottom/top for others depending whether it's up or down.
Example from the tests:
> Stem not linking to note head at correct place

- tools/visual_regression.sh
this PR specify the  -highlight-color option to 'compare'.
diff image is changed as follows:
anyway, I think last release binaries does not contains some recent changes. (8e86d583d65322d1b461efdd0b9805de46925b98)
> specify -highlight-color option to 'compare'.

- src/barnote.js
- src/clefnote.js
- src/timesignote.js
* this PR fix large voice bbox by implementing  https://github.com/0xfe/vexflow/issues/343#issuecomment-232233429 :
>Looks like ClefNote.getBoundingBox() is not implemented, so calling it dispatches Note.getBoundingBox() which returns null. This should be an easy fix.
* test case: <http://jsfiddle.net/184sthee/57/>
```text
old:
...
ClefNote:  Object { x: 0, y: 0, w: 0, h: 0 }
TimeSigNoteNote:  Object { x: 0, y: 0, w: 0, h: 0 }
BarNote:  Object { x: 0, y: 0, w: 0, h: 0 }
new:
...
ClefNote:  null
TimeSigNoteNote:  null
BarNote:  null
```
* the followings are not affected by this PR:
```
$ npm test
...
You have 1 warning(s):
Warning: NoteHead.Various_Heads.svg missing in ./build/images/blessed.
You have 5 fail(s):
Percussion.Percussion_Notes 8.58544
Percussion.Percussion_Snare1 6.38658 …
```
> {Clef, TimeSig, Bar}Note.getBoundingBox: changed to call Note.getBoundingBox() to fix large voice bbox.

- src/system.js
For example, if `right_bar: false` was passed in the `options` object, it wasn't being respected. This PR fixes that.
I'm using this change successfully in code. However, I'm not set up to be able to run the tests yet.
Please let me know if I'm missing something here. This is my first PR to VexFlow. It seemed a bit obvious that the existing options should be used rather than defining a new `const options`, so I may be missing some context that a more experienced contributor will see.
This is a fantastic project. I've started using it only in some still experimental/unreleased code on SightReadingMastery, but I am super impressed so far. Cheers to Mohit and everyone who has worked hard to make it so great!
> Prevent System.addStave from swallowing passed options

- package-lock.json
- package.json
This mainly updates npm to 6.4.1. Without this, npm audit shows 20 moderate vulnerabilities when having vexflow as an npm dependency in another project, and 35 vulnerabilities, one high, when doing npm install in vexflow. There shouldn't really be a security concern, but one shouldn't have these warnings then, either.
After this, it's 0 vulnerabilities for Vexflow as a npm dependency in another project, and 4 low vulnerabilities, one moderate for Vexflow devDependencies. All tests still pass, seems like no breaking changes.
`npm audit` now runs automatically at the end of npm install with npm 6.x, and it doesn't look nice to have these warnings when using Vexflow as a dependency.
The npm 6.4.1 update is enough to eliminate these 20 vulnerabilities, so that's the most important change.
The …
> chore: fix 20 npm vulnerabilities by updating npm (6.4.1) etc.

- src/articulation.js
GraceNotes weren't able to have articulation before, because articulation.js only checked whether the note's category is 'stavenotes', not 'gracenotes'. GraceNote extends StaveNote.
Of course it would be ideal to check whether something is a superclass of StaveNote, but Javascript isn't good enough with type detection and inheritance, right?
Now we can have some funky grace note articulations:
Tests pass.
> fix(articulation): Grace notes can now have articulation

- src/svgcontext.js
* this PR {save/restore} svgcontext.lineWidth to fix #656.
* Previously, stroke results of {svg and canvas} context were different, but now they are similar.
* many tests are affected by this PR as follows (is an excerpt):
> changed to save and restore svgcontext.lineWidth.

- tests/formatter_tests.js
This PR fixes `Warning:  Unsorted keys in note will be sorted. See https://github.com/0xfe/vexflow/issues/104 for details.` on `{npm|grunt} test`:
master:
```
$ npm test
...
Running "qunit:files" (qunit) task
Testing tests/flow.html .....................................................................................................................................Warning:  Unsorted keys in note will be sorted. See https://github.com/0xfe/vexflow/issues/104 for details. undefined
.Warning:  Unsorted keys in note will be sorted. See https://github.com/0xfe/vexflow/issues/104 for details. undefined
.Warning:  Unsorted keys in note will be sorted. See https://github.com/0xfe/vexflow/issues/104 for details. undefined
.Warning:  Unsorted keys in note will be sorted. See …
```
> [tests]: fix unsorted keys error.

- src/stavenote.js
This PR fixes #672.
- npm test:
```shell
silk@ubuntu ~/work/github/sug1no/vexflow (672-restore_note_colors=)
...
Running 298 tests with threshold 0.01 (nproc=8)...
Progress : [########################################] 100%
Results stored in ./build/images/diff/results.txt
All images with a difference over threshold, 0.01, are
available in ./build/images/diff, sorted by perceptual hash.
Success - All diffs under threshold!
```
- <http://jsfiddle.net/s5cg3fq2/4/> :
> #672: changed to remove unnecessary ctx.save call.

- src/fraction.js
This PR fixes #670.
@dolphinxx san: Thank you for your detailed comment!
- Since `Fraction.subtract` supports numeric argument, changed to support numeric argument with `Fraction.copy` (not `Fraction.equals`).
- npm test (with master):
```shell
(670-fix_durationToFraction=)
...
Results stored in ./build/images/diff/results.txt
All images with a difference over threshold, 0.01, are
available in ./build/images/diff, sorted by perceptual hash.
You have 4 fail(s):
StaveNote.StaveNote_Draw___Slash 0.50734
Rhythm.Rhythm_Draw___slash_notes 0.426776
StaveNote.StaveNote_BoundingBoxes___Treble 0.201863
Rhythm.Rhythm_Draw___beamed_slash_notes__some_rests 0.191847
```
- {1/2, 1} slash note head now correctly rendered.
- …
> #670: Fraction.copy: support 'number' type argument to fix Fraction.equls(number).

- tests/fraction_tests.js
- tests/run.js
- tests/vexflow_test_helpers.js
https://github.com/0xfe/vexflow/pull/676#issuecomment-438295893
> Can we add a test for Fraction.subtract(2) etc. to make sure bug never reoccurs? Thanks!
This PR adds some Vex.Flow.Fraction (number type argument) tests (please add more detailed tests).
- npm test (with master): Success:
```shell
(670-676_add_Fraction_tests=)
...
Running "qunit:files" (qunit) task
Testing tests/flow.html
...
....................................OK
>> 666 tests completed with 0 failed, 0 skipped, and 0 todo. 
>> 2967 assertions (in 21372ms), passed: 2967, failed: 0
Done.
...
> npm run generate:current && npm run generate:blessed
...
Running 298 tests with threshold 0.01 (nproc=8)...
Progress : [########################################] …
```
> add some Vex.Flow.Fraction (number type argument) tests.

- src/stave.js
- src/stavebarline.js
- src/stavemodifier.js
- tests/stave_tests.js
This PR fixes #547.
<https://jsfiddle.net/0ogxdft3/> :
npm tests:
```shell
sug1no@ubuntu ~/work/github/sug1no/vexflow (547-fix_end_repeat_barline_width-2 $=)
$ git log --oneline | head
218a85d add StaveModifier.{get, set}LayoutMetrics to define Barline metrics to fix stave end modifier layout.
3deef24 {WIP}: add Stave End Modifiers Test.
0bdefaf Merge pull request #676 from sug1no/670-fix_durationToFraction
ff3b4b8 Merge pull request #677 from sug1no/672-restore_note_colors
...
sug1no@ubuntu ~/work/github/sug1no/vexflow ((3deef24...))
$ grunt clean && git checkout master && npm start && git checkout @{-1} && npm test
Running "clean:0" (clean) task
...
Running 298 tests with threshold 0.01 (nproc=8)...
Progress : [########################################] 100%
Results stored in …
```
> #547: add StaveModifier.{get, set}LayoutMetrics to define Barline metrics to fix stave end modifier layout

- src/svgcontext.js
safari(12.0.1(13606.2.104.1.2)): `getBBox()` returns too large bbox with empty text element as follows:
To avoid this quirk, ignore empty text in svgcontext.fillText.
<http://jsfiddle.net/h84ekn3c/>
npm test (with master):
```shell
sug1no@ubuntu ~/work/github/sug1no/vexflow (svgcontext_ignore_empty_text $=)
$ grunt clean && git checkout master && npm start && git checkout @{-1} && npm test
Running "clean:0" (clean) task
>> 1 path cleaned.
Done.
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
...
Running 298 tests with threshold 0.01 (nproc=8)...
Progress : [########################################] 100%
Results stored in ./build/images/diff/results.txt
All images with a difference over threshold, 0.01, are
available in ./build/images/diff, sorted by perceptual …
```
> svgcontext.fillText: ignore empty text to fix large bbox of StaveLine (or others with empty text)

- src/element.js
- src/factory.js
- src/ghostnote.js
- src/notesubgroup.js
- src/stave.js
- src/stavenote.js
- src/tabnote.js
- src/voice.js
- tests/run.js
- tests/style_tests.js
This PR fixes #692.
```shell
(base) sug1no@ubuntu ~/work/github/sug1no/vexflow (692-apply-modifier-styles $=)
$ git log --oneline
f745604 {WIP}: add Element.drawWithStyle() to apply styles on draw {modifiers, tickables, subNotes}.
78ed810 {WIP}: add style_tests.js.
8a4b0c8 {WIP}: fix space.
0793189 Committing release binaries for new version: 1.2.88
29b550b Release v1.2.88
4040ea2 Merge pull request #690 from sschmidTU/master
...
###############################################
###############################################
(base) sug1no@ubuntu ~/work/github/sug1no/vexflow ((78ed810...) *$%)
Previous HEAD position was 78ed810... {WIP}: add style_tests.js.
Switched to branch 'master'
Your branch is up-to-date with …
```
> #692: apply modifier styles

- src/stave.js
- tests/factory_tests.js
This change ensure that REPEAT_BEGIN barlines are correctly aligned in a system with multiple staves.
Before:
After:
> Fix repeat barline alignment

- src/tuplet.js
- tests/tuplet_tests.js
fix #699:
```shell
(base) sug1no@ubuntu ~/work/github/sug1no/vexflow (699-fix-tuplet-number-glyph-order $)
$ git log --oneline
00d5c75 Tuplet: rename num_glyphs to numerator_glyphs.
56476c7 Tuplet: fix order of the glyphs.
d58cfce Tuplet.awkward: changed number of notes from 11 to 12.
b6a3748 Merge pull request #688 from mvolganli/fix-repeat-barline-alignment
...
(base) sug1no@ubuntu ~/work/github/sug1no/vexflow (699-fix-tuplet-number-glyph-order $)
...
> vexflow@1.2.89 diff /home/sug1no/work/github/sug1no/vexflow
> ./tools/visual_regression.sh
Running 303 tests with threshold 0.01 (nproc=8)...
Progress : [######################################--] 96%
Test: Tuplet.Awkward_Tuplet
PHASH value exceeds threshold: 3.43239 > …
```
> 699 fix tuplet number glyph order

- src/beam.js
- tests/beam_tests.js
Fix to render properly on the case, [8th - 32nd - 16th] beam(32nd partial beam is rendered incorrectly).
Add a partial beam test case.
——
I added a new test case for verifying this, and all existing test cases are passed.
Previous:
Current:
Thanks!
> Fix beam.js partial beam rendering bug,

- src/stavenote.js
- tests/dot_tests.js
Dots are rendered incorrectly on the specific condition below:
=> Displaced (ex. c/4 + d/4 in treble clef) chord note has dot and "beam".
Update StaveNote setBeam function to re-calculate extra px to ignore flag and consider beam properly
I simply updated Dot.Basic test case to also consider beamed chord note case.
Before
Current
Thanks!
> Fix dotted-beamed-displaced chord note rendering bug,

- src/beam.js
- tests/beam_tests.js
Hi, I am GeunYeong Cheon and I found that beam direction is slightly different as I thought in specific partial beam case. I added one test case in `partial_beam` test.
To get a correct beam direction, looking up the upper level beam lines'
direction is needed. Therefore, I made lookupBeamDirection to check
direction.
I tested using `npm test` with `release version` and `build version` - build version includes my modification -.  Also after running `npm test` and it shows that all test cases are passed except the one that I added.
Before
Current
Difference
Thanks!
> Fix beam direction in partial beam cases

- src/keysignature.js
- tests/keysignature_tests.js
This PR fixes #689. Several clefs defining 'customLines' had been the subject of this problem. Apply the accidental staff line placement to cancelKey and key separately to solve the problem:
https://github.com/0xfe/vexflow/blob/3920d50c95ec0e1a8d4bc96387e9ea2a1735319e/src/keysignature.js#L180
```shell
(base) sug1no@ubuntu ~/work/github/sug1no/vexflow (689-fix-cancel-keysig-2 *$%)
$ git log --oneline 
a4e5933 fix lines of accidencals to cancel.
8405983 *{WIP}: add VF.Test.KeySignature.keysCanceledForEachClef.
d5759da Merge pull request #703 from panarch/master
3920d50 Fix dotted-beamed-displaced chord note rendering bug,
...
---
(base) sug1no@ubuntu ~/work/github/sug1no/vexflow ((8405983...) $)
...
You have 1 warning(s): …
```
> 689: fix accidental staff line placement

- package.json
This implements solution 2 from #720 
This change was made because the npm version used by vexflow (^6.5.0) has a security vulnerability.
npm ^6.50 relies on an old version of a package called 'https-proxy-agent'.
When a user adds vexflow to his project (npm install vexflow), he'll get a message that his project has 21 security vulnerabilities.
This change aims to fix those vulnerabilities by moving npm to devDependencies, which are not downloaded during `npm install vexflow`
> is#720 Move npm from package.json dependencies to devDependencies

- Gruntfile.js
Many code minimizers will retain comments that begin with `/**!` or `/*!` so if the code goes through a minimizer (even a minimizer of a minimizer) this will help others keep their license obligations.
> Add `!` to Banner comment

- src/stave.js
currently, if you want to getModifiers by category, you HAVE to have a position. This seems silly.
> Feature: Allow getting all staff modifiers by category, without position

- src/canvascontext.js
- src/renderer.js
fix #742
old behavior:
browser canvas element crashes when width or height > 32767 used on renderer.resize()
https://jsfiddle.net/2Lsme8yd/
new behavior:
renderer.resize() automatically crops dimensions to 32767 and gives warning
https://jsfiddle.net/tm9qaLzb/
npm test ran without fails.
(note that this only applies to CanvasContext, not SVGContext)
> Limit CanvasContext to max browser width/height, warn

- tests/bach_tests.js
In measure 6 of the Bach Minuet Demo test, the B natural was written as "B5/q", whereas it should be "B4/q".
> Fix a note, which was an octave to high

- README.md
The link to the build instructions lead to an empty wiki page. I assume it should point to the "build and Release" page, right? If not, please delete this PR.
> Fix link to the "build" instructions

- src/multimeasurerest.js
fix MultiMeasureRest with `number_line` options:
https://github.com/0xfe/vexflow/blob/be50e3b9fb6788b9f8a32e48bb333d4c04cdbc38/tests/multimeasurerest_tests.js#L34
```
$ git checkout master && npm start && git checkout fix-multi-rest-test2 && npm test
...
You have 1 fail(s):
MultiMeasureRest.Simple_Test 5.53174
```
> VF.Test.MultiMeasureRest: fix number_line option.

- src/articulation.js
- tests/easyscore_tests.js
I found the EasyScore hook in `articulation.js` was only allowing staccato and tenuto, so I added support for accents as well and updated the test for it.
> Added support for accent articulations in EasyScore

- src/gracenote.js
- gives possibility to set glyph_font_scale and stroke_px just like StaveNote
> Merge note_struct options for GraceNote

- src/easyscore.js
- tests/easyscore_tests.js
This PR fixes #782.
```
2) commit 252050a09b2010733eb6899c68fa1cb0a0e227fd (HEAD -> fix-easyscore-dots3)
Author: h-sug1no <59550999+h-sug1no@users.noreply.github.com>
Date:   Mon Apr 27 14:06:23 2020 +0900
drawDotsTest: remove setMode(VF.Voice.Mode.SOFT).
commit 5a58d2bb77b5a31fe1eb5ac74e95425b80d76f1f
Author: h-sug1no <59550999+h-sug1no@users.noreply.github.com>
Date:   Mon Apr 27 14:05:41 2020 +0900
{WIP}: fix easyScore DOTS.
1) commit 58c16a068f2236aa8cbe3e3cc464d9823fd437c9
Author: h-sug1no <59550999+h-sug1no@users.noreply.github.com>
Date:   Mon Apr 27 14:04:55 2020 +0900
{WIP}: add VFT.EasyScore.drawDotsTest(Temporarily with Voice.Mode.SOFT).
0) commit bcf9e7c8386a73c143e714e72bcf66641fdc0f2a (upstream/master, origin/master, origin/HEAD, master)
Merge: 05cec53 c649f20
Author: Mohit …
```
> Fix easyscore dots

- src/stave.js
- src/staverepetition.js
- src/stavevolta.js
- tests/stave_tests.js
Fixes #735.
Code is mostly from suggestions from there, though the fix in staverepetition.js was a bit more complex.
Added new test `Volta + Modifier Measure Test`.
before:
after:
qunit tests and visual regression tests pass.
(there's one diff in the visual regression test,  Easy Score Draw Options, but i think that's from a different change and the blessed image wasn't updated)
> Fix volta length with modifiers, D.S. position

- src/tabnote.js
This makes it so that a tabnote can be found as a group in the svg DOM.
The same was already possible for stavenote (shown as `<g class="vf-stavenote"...`).
`npm test` passes except for one visual diff in EasyScore.Draw_Options, which i don't think i affected.
> add context/svg group for tabnote

- src/stavenote.js
- src/stem.js
- src/stemmablenote.js
- tests/stavenote_tests.js
Behind Bars, p. 14: Stems for notes on more than one ledger line extend to the middle stave-line.
Subclasses getStemExtension on stavenote to account for the height of the note.  As notes get further from Mid line (b/4 in t.c.) stems get longer (unless they go the opposite direction).  Does nothing to non-stem notes like whole notes.
Adds new test and visual test:
Fixes behavior in about 18 tests.  Example:
Blessed:
New:
Diff:
Improves beam angles in several tests:
Blessed:
New:
Diff:
It makes more obvious an existing bug in a current test.  The accent mark and the fermata on the last note of the first measure here appear to be on top of each other, but actually they are separated by 1/2 line space, similar to the staccato and accent on blessed g/5 in m. 1.  Solution will come in another …
> Stem length to middle line

- src/easyscore.js
- src/frethandfinger.js
- tests/easyscore_tests.js
- tests/stavenote_tests.js
I added support to specify fingerings using EasyScore and followed the same pattern previously established with articulations (see `easyScoreHook` in `articulation.js` for comparison).  Before this change, I was adding fingerings by doing something like this:
```
system.addStave({
voices: [
score.voice(score.notes('C4/q, E4, G4, C4'))
]
}).addClef('treble').addTimeSignature('4/4');
system.parts[0].voices[0].tickables[0].addModifier(0, vf.Fingering({ number: '1' }));
```
Now it can be specified directly in EasyScore:
```
system.addStave({
voices: [
score.voice(score.notes('C4/q[fingerings="1"], E4, G4, C4')),
]
}).addClef('treble').addTimeSignature('4/4');
```
> Added support for fingerings in EasyScore

- src/beam.js
- src/chordsymbol.js
- src/easyscore.js
- src/factory.js
- src/formatter.js
- src/glyph.js
- src/index.js
- src/note.js
- src/staveline.js
- src/stavenote.js
- src/tables.js
- src/tickable.js
- tests/accidental_tests.js
- tests/annotation_tests.js
- tests/beam_tests.js
- tests/clef_tests.js
- tests/formatter/tests.js
- tests/keysignature_tests.js
- tests/multimeasurerest_tests.js
- tests/ornament_tests.js
- tests/rhythm_tests.js
- tests/stave_tests.js
- tests/stavenote_tests.js
- tests/tabslide_tests.js
The call to drawLedgerLines method when put out of vf-stavenote group makes the drawn ledger lines to be not easy to remove from the stave. By keeping them together within the vf-stavenote group, one can remove a note and the corresponding ledgerline by doing just this:
`note.attrs.el.remove();`
> Put drawLedgerLines() within stavenotegroup

- src/chordsymbol.js
- tests/chordsymbol_tests.js
When there are a few chord symbols and many notes, it is often desirable to ignore the width of the chord symbol and let the music flow normally.
With `reportWidth = true:` (default)
With `reportWidth = false:`
This change also uses the new TextFont class for text font metrics, vs reading it from the text fonts directly like I originally did.
> Opt-out of reporting width for chord symbols

- tests/annotation_tests.js
- tests/articulation_tests.js
- tests/bend_tests.js
- tests/dot_tests.js
- tests/gracenote_tests.js
- tests/key_clef_tests.js
- tests/keysignature_tests.js
- tests/notehead_tests.js
- tests/percussion_tests.js
- tests/rests_tests.js
- tests/rhythm_tests.js
- tests/stave_tests.js
- tests/staveconnector_tests.js
- tests/stavemodifier_tests.js
- tests/stavenote_tests.js
- tests/tabnote_tests.js
- tests/tabstave_tests.js
- tests/timesignature_tests.js
- tests/vibrato_tests.js
This PR fixes new keyword mess:
```typescript
// new keyword is not needed. contextBuilder is just a function, not a constructor
var ctx = contextBuilder(options.elementId, 600, 200); 
// new keyword is not needed. Formatter() is just a factory method in Factory class, not a constructor
var vf = VF.Test.makeFactory(options, 300);
vf.Formatter().joinVoices([voice, voice2]).formatToStave([voice, voice2], stave); 
```
@0xfe I ask for a quick review. It is a really straightforward and small PR, but it will help me to continue my work on ts migration
> fix new keyword mess

- Gruntfile.js
- tests/keysignature_tests.js
- tests/vexflow_test_helpers.js
See the corresponding issue for an explanation. Here is also a stackoverflow problem:
https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne
@rvilarl FYI
> Add js files to ts-loader

- typedoc.ts
Missing exports in typedoc for documentation.
> typedoc exports

- src/fonts/bravura_metrics.ts
The visual diffs are very minimal, and only noticeable at context scale 2 or higher.
However, I did notice one visual diff that is noticeable at 1x scale. Since the `Annotation.TabNote_Annotations` test does not include round note heads, it is more obvious that the height of the note stems has changed. Please see images below. Perhaps this is something that would require a special case, to make sure **stems without note heads** have identical heights whether they are going up or down.
> Fix small issue where parts of the stem are visible around the note head. This patch affects the Bravura font.

- package.json
- tests/vexflow_test_helpers.js
- tools/generate_png_images.js
- tools/visual_regression.sh
This change allows us to render visual diff images for all three fonts.
runNodeTest() now tests all three fonts, and outputs images files with names like:
```
Accidental.Basic.Bravura.png
Accidental.Basic.Gonville.png
Accidental.Basic.Petaluma.png
...
Vibrato.Harsh_Vibrato.Bravura.png
Vibrato.Harsh_Vibrato.Gonville.png
Vibrato.Harsh_Vibrato.Petaluma.png
```
This allows us to tweak individual fonts and use `npm run test:reference` to see the changes via visual diff.
> Test All Fonts

- .vscode/settings.json
Makes it easier to search in VS Code, because we now ignore build files placed in `releases/`.
> Add releases/ to vscode's search.exclude.

- Gruntfile.js
- package.json
It will trigger the correct webpack task when it notices a changed file.
This is an alternative to an earlier PR proposal: https://github.com/0xfe/vexflow/pull/961
I actually prefer this PR, because it updates 'grunt watch' to use the webpack tasks, so it handles TypeScript files gracefully.
I decided to not include the `package-lock.json` in the PR, so that the diff is easy to understand.
If Mohit decides to merge, he can do a npm install on his machine and then check in the new `package-lock.json`.
I've tested this version and am happy with it. I drag flow.html into my local browser, and edit either src/* files or tests/* files and it recompiles quickly. Then I just CMD+R my browser to run the tests again.
> Update 'grunt watch' to watch src/ and tests/ concurrently.

- src/registry.ts
Small change.
Improving the Registry class with more correct typings.
> Registry: methods that return this should use the 'this' return type.

- src/glyphnote.ts
- src/modifiercontext.ts
- tests/glyphnote_tests.js
This change allows modifiers to be attached to GlyphNotes.  This is used to notate chord changes in an improvised solo.
> Allow modifiers like ChordSymbol to be attached to GlyphNotes.

- src/music.ts
In reviewing music.ts, I noticed that sometimes we were incorrectly comparing against `null`. For example: https://github.com/0xfe/vexflow/blob/3e13b92cc7437d5c6ac2b23fa2d056bb1f0f1564/src/music.ts#L192-L197
When we expect a number (as in the example above) or an undefined parameter (see below), comparing against `null` is incorrect.
https://github.com/0xfe/vexflow/blob/3e13b92cc7437d5c6ac2b23fa2d056bb1f0f1564/src/music.ts#L296-L297
Well, this latter line is actually fine... since undefined is falsy and null is falsy so it will do the right thing. :-D
This PR improves consistency so that we:
- check against undefined / null with strict equality operators ===
- utilize optional parameter syntax when appropriate.
> Fix inconsistencies with the way we check against null vs. undefined.

- src/barnote.ts
- src/stave.ts
- src/stavebarline.ts
The `Barline.type` getter just returns `BarlineType`. I did not remove the getter, in case it is important for backwards compatibility.
However, I replaced instances of Barline.type in the VexFlow library with `BarlineType`, to skip the getter.
Tests remain unchanged for now. We can fix them as we migrate tests to TS.
> Replace instances of Barline.type with BarlineType.

- src/stringnumber.ts
I removed the duplicated for loop in issue: https://github.com/0xfe/vexflow/issues/1013
I verified that the outer loop was never run more than once even though the inner one goes up to 3 times, with some awesome println debugging.
```
console.log('outer for loop ' + i);
...
console.log('inner for loop ' + i);
```
Tests pass with no diffs.
> Fix duplicated for loop: issue https://github.com/0xfe/vexflow/issues/1013

- tests/flow.html
For example:
`flow.html?ver=(build|reference|releases)`
You can open different versions in different tabs and switch between them to see the visual differences.
> Add `ver` query param to flow.html to allow switching between different vexflow builds.

- package.json
- src/annotation.ts
- src/chordsymbol.js
- src/element.ts
- src/font.ts
- src/formatter.ts
- src/glyph.ts
- src/gracenotegroup.ts
- src/index.js
- src/tables.js
- tests/vexflow_test_helpers.js
- tools/generate_png_images.js
Fixes https://github.com/0xfe/vexflow/issues/1026
I also turned on visual diffs for **all three fonts by default**.
For faster development, each individual developer can temporarily diff fewer fonts by customizing `generate_png_images.js` line 20. Before sending in a PR, the developer should make sure to run the visual diff for all three fonts.
In the future, we can add a npm script to allow testing of fewer fonts.
> Fix #1026 by using Flow.DEFAULT_FONT_STACK instead of a constant DefaultFontStack.

- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/petaluma_metrics.ts
- src/formatter.ts
- src/stave.ts
- src/system.js
- tests/formatter_tests.js
Currently Formatter.formatToStave uses the pre-first-note padding but does not consider padding at the end of the measure.  Also, the formatting doesn't really consider end padding at all, so the actual end point of the bar is pretty inconsistent.
2 new metrics are defined for stave:  endPaddingMin and endPaddingMax.  default padding for calculation purposes is `padding + endPaddingMax`.  The formatter decides the current format fits within the measure if the right-most point is > `staffWidth - endPaddingMin` and < `staffWidth - endPaddingMax`.
Note that many test cases don't actually use formatToStave (even some that think they do) due to some other bugs that will be addressed in other changesets.
Here is a test case that _does_ use formatToStave.  Three images, pre-changes, changing …
> Correct staff padding to include end padding

- src/beam.ts
I found a very tiny bug where it's checking for empty array using `notes === []`, which is always false because `[] !== []` in JavaScript. Changed to `notes.length === 0`.
Searching the code base, the file `src/beams.ts` is the only place where this comparison was used.
> Correctly check for empty array

- src/accidental.js
- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/petaluma_metrics.ts
I thought it made sense to do the actual formatting changes first, b/c it's hard to evaluate the success of an estimate if there are formatting issues.
This just adds 2 pixels of padding to an accidental block, so they don't get squished against the notes to the left.  Also moved a couple of formatting magic numbers to metrics.  
Before:
After, 1px padding:
After, 2px padding (this PR):
> Add additional padding to left of accidentals

- src/system.js
stave with padding needs to consider both beginning and ending padding.
> fix formatting merge bug in system.js

- src/flow.ts
While working on migrating test pages, I cleaned up flow.ts a bit. I extracted that change into this PR so it's easier to review.
In addition to sorting the imports and keys, I removed two entries that don't seem to be used anywhere on the test pages (and they are also not in version 3.0.9).
`PetalumaScriptTextMetrics`
`RobotoSlabTextMetrics`
I believe those two are used exclusively by `textfont.ts`, so they should be local to that file.
> Flow.ts: Use shorthand property names. Sort imports and keys.

- src/stave.ts
- src/system.ts
- tests/factory_tests.js
- tests/formatter_tests.js
Possibly final issue with bug 846. 
If system is created with autoWidth set to true, it will calculate use formatter.preCalculateMinWidth and justify all voices.
autoWIdth flag is set by default if no width is provided, and justification is not specifically disabled with a flag.  I'll paste before/after.
> use formatter.preCalculateMinWidth in system/factory

- src/canvascontext.ts
- src/renderer.ts
- src/svgcontext.ts
- src/types/common.d.ts
- tests/annotation_tests.js
Many test cases set the `fillStyle`, `strokeStyle`, and `font` directly via setters. However, `SVGContext` and `CanvasContext` did not actually implement those setters.
For example, if we write code like this:
```
ctx.fillStyle = '#F21';
ctx.strokeStyle = '#F21';
ctx.font = '10pt Arial';
```
It will only affect the CanvasContext, since the web browser's native `CanvasRenderingContext2D` implements those setters.
I added the setters so that now it also works with `SVGContext`. See below for before/after:
One question: We never actually create any CanvasContext objects. There are no test cases that set `Renderer.USE_CANVAS_PROXY` to true. What types of environments require us to use the CanvasContext() object?
```
if (Renderer.USE_CANVAS_PROXY) {
return new CanvasContext(ctx);
}
``` …
> Add missing setters to maintain compatibility with CanvasRenderingContext2D API

- src/music.ts
`music.noteValues` is used by smoosic. Assumption of private element was wrong.
fixes #1084
> restore `music.noteValues`

- tools/generate_png_images.js
Now that PR #1074 has been merged, it has become the new 'reference'. Thus generate_png_images.js needs to load the 'reference' library the new way (one JS file). 
Fixes #1088.
> Restore the ability to run 'npm run test:reference' 

- src/tables.ts
- src/tabnote.ts
- src/tabslide.ts
- tests/textnote_tests.ts
TabNoteStruct: Use `number | string` for fret positions. Handle edge cases. Fixes: https://github.com/0xfe/vexflow/issues/1093
Unicode: Remove `parseInt()` because I think JS engines should be able to deal with numbers starting with `0x`. Add comments showing the unicode output. Fixes: https://github.com/0xfe/vexflow/issues/1087
**No visual diffs from master.**
I have been using a VS Code extension called "TypeScript Import Sorter" so the imports are getting alphabetized by module name when I save the file. At some point we can add a [eslint rule](https://eslint.org/docs/rules/sort-imports) so we can have consistent imports. :-)
> Small fixes to TabNoteStruct and Unicode

- Gruntfile.js
- demos/README.md
- demos/node/README.md
- demos/node/canvas.js
- demos/node/svg.js
- src/renderer.ts
Requiring releases under Node.js will throw an error:
```
})(window, function() {
^
ReferenceError: window is not defined
```
REF: https://github.com/webpack/webpack/issues/6522
After checking the history, I can confirm that it is a problem after upgrading Webpack above 4.x: https://github.com/0xfe/vexflow/pull/1045#discussion_r674445728 and 0802a99 has set `globalObject: 'this'` to solve the problem, but it is not a perfect way.
Other:
- Support passing elements directly when constructing `Renderer`s, so that developers can:
1. Use [`node-canvas`](https://github.com/Automattic/node-canvas) to render with this tool.
2. Use [`jsdom`](https://github.com/jsdom/jsdom) to simulate and generate SVG headlessly.
> Fix wrong global definition genereated by Webpack in UMD styles

- src/fraction.ts
- tests/fraction_tests.ts
Use `if (typeof n === 'number') {` instead of `instanceof Fraction` to differentiate between Fraction objects and numbers.
Added more tests to exercise the Fraction API, including tests for `Fraction.LCMM()`, which was previously untested. 
This PR partially addresses: https://github.com/0xfe/vexflow/issues/1096
No visual diffs.
> Remove instanceof from Fraction.

- src/font.ts
- src/glyph.ts
- src/tables.ts
- tests/boundingboxcomputation_tests.ts
These optimisations speed up the time spent during parsing and rendering the "Bach demo" test by a factor of approximately 1.6 in both Chrome and Firefox on my machine. The total time spent running all tests is reduced from approximately 16 seconds to 12 seconds.
Some more details:
- Convert the cached outline from an array of strings to an array of integers. This avoids repeatedly calling `parseInt` whenever the outline is processed.
- Cache the glyph metrics and bounding box, which avoids repeatedly loading the metrics and parsing the outline data.
- Add a static `Glyph.getWidth` method that calculates the width from the cached bounding box rather than creating a complete `Glyph` object when only the width is needed.
- Replace all the implementation of the `getWidth` calls in …
> Optimizations to the glyph code

- tsconfig.dynamic.json
- tsconfig.json
Fix https://github.com/0xfe/vexflow/issues/1106
I checked that `npm run test:reference` passed with zero visual diffs.
> Change target to es6.

- tests/staveconnector_tests.ts
Summary: doing so allows us to alphabetically sort the tests and test imports in `run.ts` without breaking things.
---
In an older version of VexFlow, ( circa Oct 2015 / commit b8d27229d2ac69d732d7b8df0b4b75c1b6c8a609 ) `STAVE_LINE_THICKNESS` was 2 by default. Currently it is 1.
`staveconnector_tests` had a test case that temporarily set the thickness to 1, and then changed it back to 2. This worked back in the day, but now that the default is 1, it has the problem of permanently changing the thickness away from the default for all test cases that come after the StaveConnectorTests.
This PR results in 363 visual diffs, all related to the stave lines in test cases that were run after `StaveConnectorTests.Start()`;
The *reference images were wrong* because they do not render the stave lines …
> Fix a test case that permanently modified Vex.Flow.STAVE_LINE_THICKNESS

- src/accidental.ts
- src/articulation.ts
- src/clef.ts
- src/easyscore.ts
- src/element.ts
- src/font.ts
- src/formatter.ts
- src/glyph.ts
- src/keysignature.ts
- src/modifier.ts
- src/multimeasurerest.ts
- src/note.ts
- src/notehead.ts
- src/ornament.ts
- src/stavemodifier.ts
- src/stavenote.ts
- src/tables.ts
- src/tabnote.ts
- src/textdynamics.ts
- src/textnote.ts
- src/tickable.ts
- src/timesigglyph.ts
- src/timesignature.ts
- src/tuplet.ts
- src/util.ts
- src/voice.ts
Also omit type `<T>` from calls to `defined(...)` when possible.
Some classes already have `checkStave()`. Implement `checkStave()` as a convenience method in other classes.
> Rename check<T>() to defined<T>().

- src/easyscore.ts
- src/factory.ts
- src/music.ts
- src/parser.ts
- tests/chordsymbol_tests.ts
- tests/parser_tests.ts
Use TypeScript's Partial<Type> for EasyScoreOptions.
Use spread operator instead of Object.assign, as discussed in https://github.com/0xfe/vexflow/pull/999#discussion_r641946148
Parser should not know about EasyScore. Grammar is now a simple interface with one required begin() function.
> Clean up EasyScore & Parser.

- Gruntfile.js
Fix a minor regex bug in `Gruntfile.js`. The regex was previously matching files that end in `.t`, .`ts`, `.j` or `.js`. Fix it to only match `.ts` and `.js`.
> Minor gruntfile fix

- src/canvascontext.ts
- src/renderer.ts
- src/svgcontext.ts
- src/types/common.d.ts
- tests/stavenote_tests.ts
This PR makes the shadow/glow appearance consistent across the SVG context and canvas contexts at different device pixel ratios. The old SVG glow code is deleted and replaced with a `drop-shadow` CSS filter, a feature that now has more than [95% browser support](https://caniuse.com/?search=drop-shadow).
It also fixes a bug with the canvas shadow where the shadow blur radius wasn't being scaled by the canvas transform. It turns out that `CanvasRenderingContext2D` ignores scaling when applying a shadow. This meant that glow/shadow had a different appearance when depending on whether or not the user had a high density display.
I had to update the shadow blur sizes in the `StaveNote` tests to account for the fact that the blur radius now uses the correct units.
All visual diffs from this PR …
> Fix shadow/glow rendering

- src/factory.ts
- src/formatter.ts
- src/tickcontext.ts
This PR implements the discussion below with @ronyeh. `TickContext`does not extend `Tickable` and it follows the same approach as `ModifierContext`.
**The discussion for reference:**
Let me try my best to analyze it objectively, but I am not familiar with the original intent of `Tickable` and `TickContext`.
---
If we could make `TickContext` an independent type, then `Tickable` and `Note` could be merged.
So I investigated whether we can make `TickContext` not extend Tickable, by commenting it out `/*extends Tickable*/`.
This produces errors with these missing methods and properties:
```
this.setAttribute('type', 'TickContext'); 
this.width 
this.ignore_ticks = false;
this.setPreFormatted(false);
this.preFormatted
this.postFormatted
```
TickContext has similarities to ModifierContext. In …
> `TickContext` not extending `Tickable`

- src/canvascontext.ts
- src/renderer.ts
- src/stave.ts
- src/svgcontext.ts
- src/textbracket.ts
- src/textnote.ts
- src/types/common.d.ts
While investigating #1127, I noticed that measuring text in the `SVGContext` is quite slow because it forces a DOM reflow, so I added a cache. This reduces the time taken to run all tests from _12.5 seconds_ to _10.5 seconds_ on my machine.
In real world use cases that lay out systems one time only, this change will probably only have a marginal effect. In interactive cases, where the same page is repeatedly laid out with only minor changes each time (like my personal use case), this will greatly speed up all text measurement.
Changes in this PR:
- Return a `TextMeasure` object from `RenderContext.measureText` that has both `width` & `height`. Previously, either a `SVGRect` or `TextMetrics` object would be returned depending on whether the context was canvas or SVG. In particular, …
> Clean up text measuring & add a text measurement cache to SVGContext

- src/stave.ts
- src/stavenote.ts
- Move the default ledger line style from `StaveNote` to `Stave`. Prior to this change, a user could only change the default ledger line width by explicitly setting it on every single `StaveNote`. Now, they only have to change the default ledger line style on each `Stave`.
- Following on from the recent discussion on #1052, change the ledger lines to be thinner but darker. In the end, I chose a line width of 1.4 so that the anti-aliasing on the darker line was close to the old ledger line shade.
- Early out of `StaveNote.drawLedgerLines` if there are no ledger lines to be drawn.
I reviewed every one of the 576 image diffs that result from this PR and they were all caused by the change in ledger line thickness and stroke style, i.e. moving the default style from `StaveNote` to `Stave` had …
> A few ledger line tweaks

- src/svgcontext.ts
- src/util.ts
This PR updates the `SVGContext.arc` behaviour to match that of `CanvasRenderingContext2D`:
- The pen position should end up at the end of the arc: the code that was moving the pen back at the end of `arcHelper` was incorrect.
- If the length of the arc specified by `angleStart`, `angleEnd` and `radius` is longer than the circle's circumference, a completely closed circle should be drawn.
None of this really matters because this change doesn't cause any image diffs, but it's nice to have consistency across the contexts.
While I was here, I simplified the implementation a bit.
> Fix a couple of defects in SVGContext.arc

- src/glyph.ts
All glyphs already start with an `M` command, so the `moveTo` at the start of `Glyph.renderOutline` doesn't do anything and seems to break ImageMagick's SVG rendering for some reason.
This fixes #1150.
Output from from ImageMagick's converter: `convert bach.svg bach.png`
> Remove redundant moveTo in Glyph.renderOutline

- src/svgcontext.ts
This PR modifies SVGContext's `MeasureTextCache` to call `document.createElementNS(SVG_NS, 'text')` as late as possible.
This allows us to load VexFlow in NodeJS as in the vexflow/demos/node/ folder.
Before:
```
node demos/node/svg.js
this.txt = document.createElementNS(SVG_NS, 'text');
ReferenceError: document is not defined
at new MeasureTextCache (vexflow/build/vexflow-debug.js:26163:20)
```
After:
```
node demos/node/svg.js
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500" viewBox="0 0 500 500"><path stroke-width="1" fill="none" stroke="#999999" stroke-dasharray="none" d="M10 80L410 80"></path><path stroke-width="1" fill="none" stroke="#999999" stroke-dasharray="none" d="M10 90L410 90"></path><path stroke-width="1" fill="none" stroke="#999999" stroke-dasharray="none" …
```
> Delay call to document.createElementNS() to support loading VexFlow in NodeJS with jsdom.

- src/multimeasurerest.ts
- tests/multimeasurerest_tests.ts
This PR fixes #1147.
My apologies for the typo!  orz...
```
$ git checkout master
$ git npm run reference
...
$ git checkout fix-typo_semibrave-to-semibreve 
$ npm run test:reference
...
Running 1056 tests with threshold 0.01 (nproc=4)...
Progress : [########################################] 100%
Results stored in ./build/images/diff/results.txt
All images with a difference over threshold, 0.01, are
available in ./build/images/diff, sorted by perceptual hash.
Success - All diffs under threshold!
```
> fix typo: semibrave to semibreve.

- src/svgcontext.ts
This PR fixes a bug in `SVGContext.fillRect`.
Prior to this fix the `SVGContext` was incorrectly applying the current stroke style to the rectangle; the rectangle should be drawn without a stroke to match the behaviour of the `CanvasContext`. The most noticeable effect of this bug was that the barlines & stave connectors were drawn incorrectly.
All visual diffs caused by this change are, rather surprisingly, under the threshold.
SVG before this PR:
SVG after this PR:
Canvas:
> Don't stroke rectangles drawn with fillRect

- src/accidental.ts
- src/articulation.ts
- src/frethandfinger.ts
Minor chnage to remove unnecessary casting to `StaveNote`
> Remove "as StaveNote" from src

- src/canvascontext.ts
- src/svgcontext.ts
- src/types/common.d.ts
Add equal signs to handle the case where the arc is exactly a circle.
`>= TWO_PI`vs `> TWO_PI`
Fixes https://github.com/0xfe/vexflow/issues/1177
Rename antiClockwise to match the HTML specification naming convention:
https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-arc
> Restore SVG dots

- demos/node/README.md
- demos/node/customcontext.js
- src/canvascontext.ts
- src/factory.ts
- src/renderer.ts
- tests/renderer_tests.ts
fixes #827
fixes #724
This enables users to create their own `RenderContext` implementations.
The required a couple of changes:
- Move the `CanvasContext` resize logic out of `Renderer` and into `CanvasContext`.
- Overload the `Renderer` constructor to accept a `RenderContext`.
This PR also fixes a bug in the `Factory` where it would always create an `SVGContext` even if you passed it the element ID for a `HTMLCanvasElement`. Consequently, there are a few image diffs because the `Factory.Draw` test now actually renders something for the canvas test :)
> Allow a RenderContext to be passed directly to the Renderer constructor

- package.json
- src/multimeasurerest.ts
- tools/generate_png_images.js
- tools/visual_regression.sh
This PR contains:
- generate_png_images.js: added some options:
- `--parallel[=<jobs>]` : exec processes in parallel for each font
- `<jobs>`:
- `<jobs><=1`: explicitly to disable parallel execution
- unspecified: enable parallel execution
- otherwise: In the future, it may be possible to limit the number of processes
- `*.Bravura.png` is generated as `*.png`.
- see: https://github.com/0xfe/vexflow/blob/a4920f128ff65f683da029d76feb8a6919eb1bf4/tests/vexflow_test_helpers.ts#L223
- `--backcompat`: generate test results for Bravura fonts with old-style file names
- rename `*.Bravura.png` to `*.png`.
- visual_regression.sh: reduce execution time
- by using `cmp -s`
- package.json: added some run commands:
- environment variable for `generate*` run commands:
- VF_GENERATE_OPTIONS:
- …
> Parallel generate image 

- src/beam.ts
- src/factory.ts
- src/stavehairpin.ts
- src/stavetie.ts
- src/vibratobracket.ts
- tests/auto_beam_formatting_tests.ts
- tests/beam_tests.ts
- tests/pedalmarking_tests.ts
- tests/percussion_tests.ts
- tests/renderer_tests.ts
- tests/stavehairpin_tests.ts
- tests/stavenote_tests.ts
- tests/stavetie_tests.ts
- tests/vibratobracket_tests.ts
There are only two `ts-nocheck`pending to be resolved:
One in **textnote_tests.ts** @ronyeh could you include in #1163?
Another one in **typeguard_tests.ts** which I do not know how to resolve.
> several `ts-nocheck` resolved

- src/fonts/gonville_metrics.ts
- src/fonts/petaluma_metrics.ts
resolves #555, resolves #792 
Add/repair formatting for tremolo and grace notes for some fonts.  I am no designer and I don't have such a good eye for small visual details, but these look pretty good to me.   Gonville tremolo is hard to judge b/c it's so slanty.
before:
after:
before:
after:
> fix issues 555, 792.  Fix metrics with tremolo Gonville and Petaluma, and Petaluma grace notes

- src/stave.ts
- tests/stavetie_tests.ts
Fixes #489
**StaveTie › No End Note** 
before:
after:
No other visual difference
> fixes `getTieEndX` in `Stave` (StaveModifiers placed at the end of the Stave collide with StaveTies without end notes.)

- Gruntfile.js
@tommadams can you confirm if this patch fixes the grunt watch for you? These are the options I'm currently using on my branch.
Apologies for introducing the bug! :-)
> Fix grunt watch with correct use of the webpack `ignored` field.

- tests/formatter_tests.ts
@AaronDavidNewman as agreed in #411 I have added a test case in formatter to show this worng behaviour, could you look into a possible solution?
> Add test for issue #411

- src/formatter.ts
- src/system.ts
Fixes #1149 
Following the proposal:
- `SystemParams` -> `SystemStave`
- `...Options` class options provided to the constructor, 
- `...Params` group of parameters used on functions: `FormatOptions` -> `FormatParams`
> SystemParam / FormatOptions renamed

- Gruntfile.js
- tools/visual_regression.sh
Checking in detail the differences in #1242 I have realised that `grunt reference` was broken leaving files from previous versions.
> fix grunt reference

- src/accidental.ts
- src/formatter.ts
- src/notehead.ts
- src/stave.ts
- src/strokes.ts
fixes #1146
this PR deletes the unused options. The documentation is not addressed but this is a general issue anyway.
No visual differences.
> clean up options

- src/easyscore.ts
- tests/easyscore_tests.ts
Fixes #705
No visual changes. 
Additional tests:
**Muted**
** Harmonic **                  
**Slash**
> Easyscore support for muted, harmony, slash and ghost notes I (muted, harmony, slash)

- src/articulation.ts
- tests/articulation_tests.ts
#fixes 1267
prevent accidentals from colliding when some accidentals must be placed above/below the staff and others don't.
before:
after:
> Issue1267 artic y pos

- Gruntfile.js
- package.json
The new location in build/cjs broke the tests against a reference.
This is a minor change to take into account the location of the files.
> Bug on  "npm run test:reference" visual regression.

- src/articulation.ts
- src/beam.ts
- src/easyscore.ts
- src/frethandfinger.ts
- src/ghostnote.ts
- src/note.ts
- src/stavenote.ts
- src/tables.ts
- src/tuplet.ts
- tests/curve_tests.ts
- tests/easyscore_tests.ts
- tests/formatter_tests.ts
- tests/stavetie_tests.ts
Fixes #463
@0xfe this one includes #1259, if you merge #1259 first the number of changes will be reduced.
The support of `Ghostnotes` in `EasyScore` involves three main topics:
- Change return type of `EasyScore.notes(...)` from `StaveNote` to `StemmableNote`
- Move `AddArticulation` ... from `StaveNote` to `Note` where the handling of modifiers is already.
- Support for `GhostNote` in `Beam` and `Tuplet`
No visual diffs. Tests in addition to those in #1259:
**Basic  (replica from Ghostnote_Basic using EasyScore)**
**Dotted  (replica from Ghostnote_Dotted using EasyScore)**
> Easyscore support for muted, harmony, slash and ghost notes II (ghost)

- src/dot.ts
fixes #1274
I figured out wich circular dependency was producing the crash. This PR fixes this particular one.
I have learned that:
- methods like `note.isTabNote()` contribute to circular dependencies
- `note instanceof TabNote` produces the same error (also contributes to circular dependencies`
We should probably avoid the methods above.
> Fix Circular Dependency Issue (using getCategory)

- tools/generate_images.js
@0xfe san
thank you for merge #1268 and sorry to bother you.
this PR reduce the jsdom_jobs on platform with many cpus.
for example my MBP has 12 logical cpus. 
It seems that 12 is a bit much for jodom_jobs, so limiting it to pptr_jobs will speed up the process by a few seconds.
> reduce jsdom_jobs on platform with many cpus.

- src/canvascontext.ts
- src/rendercontext.ts
- src/stave.ts
- src/stavesection.ts
- src/svgcontext.ts
- tests/stave_tests.ts
Fixes #1253
Fixes #1256 
@sschmidTU could you review this one?
@0xfe the visual regression does not show any difference although there is the difference bellow. Do you agree with this change? To me in makes more sense to use the text meassurement hieght and the question is also if we want to add a padding up / down
**Current**
**Reference**
> OSMD VexflowPatch: stave & stavesection

- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/petaluma_metrics.ts
- src/tuplet.ts
With tuplet, annotation, and accidental CS all merged it will look like this:
I ran visual regression tests (which I figured out finally after 3 years how to do!) and there were no changes.  The logic here only kicks in if there are modifiers that take up vertical space on one of the notes the tuplet covers, and currently none of our other test cases do this.
> Fix issues of vertical placement: tuplet

- src/fonts/gonville_metrics.ts
- src/glyph.ts
- src/tremolo.ts
- tests/tremolo_tests.ts
fixes #1258
@sschmidTU could you review these changes? I do not get it right.
No visual diffs but incorrect result in new test with `Gonville` (this might be fixed once #1243 is merged):
> OSMD VexflowPatch: support for big tremolo

- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/petaluma_metrics.ts
- src/stave.ts
- src/staverepetition.ts
- src/version.ts
- tests/stave_tests.ts
Fixes #1255 
There only visual differences on the two tests below (I have just placed the Gonville results). IT IS OBVIOUSLY WRONG.
Order is:
- diff
- reference
- current
**Stave Multiple_Staves_Volta**
**Stave Volta___Modifier_Measure**
> OSMD VexflowPatch: StaveRepetition, TO_CODA support and position fix.

- src/canvascontext.ts
- src/rendercontext.ts
- src/svgcontext.ts
Minor fix: the first parameter should be optional. This parameter is expected to be undefined or a string within the function.
@sschmidTU thanks to find this out!
No visual differences.
> fix openGroup optional parameters

- src/dot.ts
- src/modifiercontext.ts
- src/note.ts
- src/parenthesis.ts
- src/stavenote.ts
Fixes #1283
After realising that the code in `StaveNote.forma()` in #1263 was dead code. I decided to bring it back to life as simple as possible.
The visual differences (Bravura version) are:
**StaveNote Center_Aligned_Note___Multi_Voice Bravura**
**Current**
**Reference**
**Three_Voice_Rests Auto_Adjust_Rest_Positions___Three_Voices__2 Bravura**
**Current**
**Reference**
**Three_Voice_Rests Auto_Adjust_Rest_Positions___Two_Voices Bravura**
**Current**
**Reference**
> simplify format function in Stave Note

- src/accidental.ts
fixes #1316 
Only one visual difference on all fonts (below Bravura):
**Current**
**Reference**
> fix #1316: consider shifted notes

- tests/ornament_tests.ts
fixes #1314 
@AaronDavidNewman thanks!
The test system shows no visual difference although there is one indeed:
**Current**
**Reference**
> fix #1314: remove duplicated line

- .gitignore
- tools/dependency_graph.js
- tools/dependency_graph.rb
I've been updating docs for https://github.com/0xfe/vexflow/issues/1271
I ran across the dependency graphs wiki page and realized the script no longer worked.
I fixed the ruby script, and then got side tracked a bit...and discovered a npm package that can produce interactive graphs. I wrote up a script, and here are the graphs I produced:
[src/ folder](https://vexflow-dependency-graphs.surge.sh/src.html)
[entry/ folder](https://vexflow-dependency-graphs.surge.sh/entry.html)
[tests/ folder](https://vexflow-dependency-graphs.surge.sh/tests.html)
You can hover over edges to show a tooltip. Click on a node to open the GitHub page for that file.
The updated docs are here: https://github.com/0xfe/vexflow/wiki/VexFlow-Class-Diagrams
I verified that the example commands now work once again.
> Dependency graphs.

- tests/articulation_tests.ts
fixes #1309 
The problem was in the test. The helper function was not providing a `Stave` to `Formatter` and as a consequence `Beam.postFormat()` was not being instantiated. 
Visual differences, only the expected one:
**Current**
**Reference**
> fix #1309: make sure that postFormat is called

- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/petaluma_metrics.ts
- src/staverepetition.ts
fixes #1313 
Another visual difference that is not detected, however the problem is resolved:
**master**
**current**
> fix #1313: segno position

- src/beam.ts
- src/stavetie.ts
Without this PR, staveties, beams and stems within beams are just random `<path>` elements in the SVG Dom, not inside a `<g>` node with a class (and sometimes id), which non-beamed stems and most other elements like key signatures and clefs are at this point:
Instead, these 3 path nodes will be within `<g class='vf-stem/beam'>`  groups too now.
There are a few differences in how the SVG classes are created.
For staveties, we just save the SVG node as an attribute 'el' to the stavetie, so the SVG node doesn't need an ID -> you can get it by `stavetie.getAttribute('el')`.
(alternatively, we could set the id by taking the ID of the start note + `-tie` if you want to get the info from the SVG alone)
Same for beams.
For stems within beams, the id of the note is added to the stem id, because …
> Add SVG classes (+ ids partly) to beams, stems within beams, staveties (OSMD VexflowPatch)

- src/annotation.ts
- src/articulation.ts
- tests/articulation_tests.ts
- tests/gracenote_tests.ts
Prevent grace notes from being pushed too far away from the note by annotations and articulations, because those modifiers reported incorrect width (too high).  For centered, vertically stacked modifiers, subtract the note width from the modifier width and report the overlap.
old:
new:
This causes 298 visual differences.  Most of them are not visible to me, if I didn't see the diff.  Our perceptive hash is super sensitive to text changes.  
Some new test cases take up less room, but I didn't see any collisions.  This is an example:
old:
new:
> fix #1295 by more accurately reporting articulation and annotation width

- tests/formatter_tests.ts
Reviewing the tests' output I thought that in the test below there was a rendering error: Some notes were missing. 
The problem is that the test did not keep num_beats contant. 
I suggest this change to avoid that someone else also thinks that the rendering is wrong. Bellow the Bravura version:
**Formatter Whitespace_and_justify Bravura**
**current**
**reference(master)**
> Formatter Whitespace_and_justify: keep num_beats constant

- src/annotation.ts
- tests/annotation_tests.ts
This PR enables rendering styles applied using the base `Element` class's `setStyle()` method when drawing annotations.
> feat(annotation): Apply styles from setStyle when rendering

- src/note.ts
- src/system.ts
Fixes #1307
This PR includes two changes:
- change in system.ts to join voices when autoWidth is set (to address #1307).
- fix the position of left parenthesis when the note is shifted (bug was made evident with the change above)
> Fix #1307: Accidentals overlapping

- src/note.ts
- src/stavenote.ts
Fixes #1331
Follows proposal from @mscuthbert on how to combine rest notes.
Visual differences (Bravura) diff/current/reference
> Fix #1331: shared rest notes

- src/flow.ts
- src/staveline.ts
- src/stavetext.ts
- src/textnote.ts
- tests/stave_tests.ts
While working on the most recent CJS/ESM PR, I noticed that we were exporting a generically named enum called `Justification` from the TextNote file: 
https://github.com/0xfe/vexflow/blob/b23bb465b2e52f2e4c50af269b79225d395f3f5b/src/textnote.ts#L10-L14
StaveLine also has an identical "enum": https://github.com/0xfe/vexflow/blob/b23bb465b2e52f2e4c50af269b79225d395f3f5b/src/staveline.ts#L65-L69
In this PR, I renamed Justification to TextJustification so that it is more clear what the enum is used for. This is similar to the convention used in other classes, like:
https://github.com/0xfe/vexflow/blob/b23bb465b2e52f2e4c50af269b79225d395f3f5b/src/annotation.ts#L20-L32
`AnnotationVerticalJustify` and `AnnotationHorizontalJustify` are long names, but it is clear what they are for.
Summary:
* …
> Rename Justification to TextJustification.

- src/stavenote.ts
fixes #1365
Only one visual difference:
**StaveNote Note_Heads_Placement___Simple Bravura**
**current**
**reference**
> fix unnecessary shift

- tests/formatter_tests.ts
Show effects of softmax with larger amounts of whitespace in a measure.  See discussion in PR 1376 which was cancelled and replaced with this one.
@rvilarl  wrote in previous PR:
>>> shouldn't we change the default from 100 to 5 as well?
>> That would change all the test cases. Do we want to do that?
>> I'm also open to making it easier to set the global softmax. It seems like it is defined in 2 places. It seemse like it should be  defined in one place, either be in tables, or in the font metrics.
I would go for that, @0xfe what do you think?
> add softmax test with more extra padding

- src/stave.ts
- src/stavesection.ts
- tests/stave_tests.ts
fixes #1366
On the refactoring of `StaveSection` the text was put half a line higher. It also allows to make the rectangle around the text configurable as requested by @sschmidTU.
Only one Visual Difference (test case changed to disable the rectangle in the first section)
> rect configurable in sections

- Gruntfile.js
- README.md
- demos/jsfiddle/gracenotes.html
- demos/jsfiddle/sandbox.html
- demos/jsfiddle/tutorial/step1_basics.html
- demos/jsfiddle/tutorial/step2_addnotes.html
- demos/jsfiddle/tutorial/step2_secondvoice.html
- docs/sandbox.html
- package.json
Work in progress:
- Adds a step to the release script where we patch version 3.0.9 with a console.warn() message to upgrade to VexFlow 4. We publish this version at the old URL to fix any live deployments that reference the old URL.
- As part of my work in updating the wiki and fixing JSFiddles, I am starting to include the JSFiddle examples in the repository itself. This will make it easier to maintain going forward. If any changes are needed (e.g., if VexFlow 5 breaks something), we can make the changes in the repo and copy the code directly into the JSFiddles, instead of editing the code on the JSFiddle editor.
> Restore v3.0.9 URLs and Fix JSFiddle examples.

- src/stavenote.ts
- tests/stavenote_tests.ts
fixes #1369
The notes which are hidden are not to be considered in the formatting calculations.
No visual differences.
> exclude hidden notes from formatting

- src/element.ts
- src/stavenote.ts
- src/stemmablenote.ts
> @0xfe @gristow would it make sense to arrange elements genericaly in a tree?
> with that we could find childs for example by className we would have a root element without parent (probably the score), childs of the scores would be the measures, child of the measures would be the notes and then we could define a setGroupStyle() that would apply to the referenced element and all its childs.
>@ronyeh @AaronDavidNewman what do you think?
POC to show the idea I described in #285 quoted above.
I have also realised that if we set a `Registry` see below,
https://github.com/0xfe/vexflow/blob/46af63bb5eb52c66d3a30d978b3a08d04eecf5c6/src/element.ts#L111
we can use the registry member fuctions to look for elements and appy styles.
> setGroupStyle

- src/factory.ts
- src/stringnumber.ts
- tests/stringnumber_tests.ts
fixes #1364
I added one test without circle (this one collides as described in #1364 without the changes in this PR).
which is a variant of the standard with radius 8
> stringnumber: radius protected, circle configurable. 

- src/stave.ts
- src/system.ts
- tests/auto_beam_formatting_tests.ts
- tests/easyscore_tests.ts
fixes #1389
fixes #1359
Beginnig stave modifiers now formated automaticaly if `System` is used, otherwise they can be aligned as shown in `auto_beam_formated_test`.
New test added to show the results.
**EasyScore Draw_Different_KeySignature** (bravura)
> format beginning stave modifiers

- src/flow.ts
- src/glyph.ts
- src/tables.ts
fixes #1152 
SVG paths with 2 decimals, all the tests have minimal visual differences, see example below.
s
> SVG paths with 3 decimal places of precision.

- src/system.ts
- tests/stavenote_tests.ts
fixes #1412
I have writen a test to look into the differences (upper stave with nopadding set to true and lower stave with nopadding set to false)
**results with the fix in this PR**
**results with master**
I believe that the result with the fix is the right one: The notes use a little more space in the stave without padding.
> fix no padding

- src/note.ts
fixes #705 
As discussed at the end of #705 duration is not optional.
@ronyeh what is your oppinion.
> notestruct duration is not optional

- tests/beam_tests.ts
This is the first step in #1427: A new test showing the issue. Also related to #1409 simplification.
> System is not handling ModifierContexts correctly with more than one Stave

- .gitignore
- src/formatter.ts
- src/keysignature.ts
- src/stave.ts
- src/stavenote.ts
- src/stavetie.ts
- src/textnote.ts
- tests/textnote_tests.ts
Fixes #1429
These are places where the music21j project have needed to break TypeScript encapsulation to read or test conversions.
(wow VF 4!  What a joy it is to edit the code now!)
> Add getters for six attributes

- src/annotation.ts
- src/beam.ts
- src/chordsymbol.ts
- src/element.ts
- src/glyphnote.ts
- src/ornament.ts
- src/stavenote.ts
- src/stavetie.ts
- src/stem.ts
- src/tabnote.ts
- tests/stavenote_tests.ts
Fixes #1445 
- use the lower case of category (typescript class name) and attrs.ID, both with prefix `vf-`. ie.: `vf-stavenote`, `vf-auto1010`
- check that the groups are grouped consistently. ie.: modifier within notehead group
- avoid duplications. ie.: `vf-notestave` containing a `vf-note`
- add the groups requested by you (@0xfe @AaronDavidNewman @ronyeh @mscuthbert @sschmidTU ) and others in this PR
> Refactor & dynamic styling (step 2 Standardize openGroup)

- src/barnote.ts
- src/element.ts
- src/notehead.ts
- src/stave.ts
- src/stavenote.ts
- Remove unneccesary check of `this.style!=undefined` before calling `applyStyle` / `restoreStyle` this already checked within these functions.
- Allow ´setStyle´ to also accept `undefined`
- Access `this.style` through `set/getStyle`function
- `flagStyle` not required, `flag` contains its own `ElementStyle`
> minor style fixes

- src/beam.ts
- src/system.ts
- src/voice.ts
- tests/crossbeam_tests.ts
- tests/index.ts
fixes #1373
ready for review now with more focus. It includes the tests from @AaronDavidNewman
> Voice cross stave support in System

- src/glyph.ts
- src/svgcontext.ts
addesses #1458 1st bullet
>- There are still elements with more than 3 digits precission. Should we make the rounding directly in SVGContext rather that in Glyph to make sure that all the elements get rounded? I think we should.
A lot of not visible minor changes. The same problem as when we introduced the rounding in Glyph. I will put some diff images examples below.
Test SVGs reduded by 900 KB
> move rounding to SVGContext

- tests/annotation_tests.ts
- tests/articulation_tests.ts
- tests/bend_tests.ts
- tests/chordsymbol_tests.ts
- tests/dot_tests.ts
- tests/notehead_tests.ts
- tests/ornament_tests.ts
- tests/rests_tests.ts
- tests/stavenote_tests.ts
- tests/style_tests.ts
- tests/tabslide_tests.ts
- tests/tabtie_tests.ts
- tests/vibrato_tests.ts
addresses #1452 
A lot of minor visual differences. I will copy the bravura ones.
> Question: Remove assignment of `fillStyle` and `strokeStyle` in tests?

- src/annotation.ts
- src/chordsymbol.ts
- tests/annotation_tests.ts
- tests/chordsymbol_tests.ts
Small change, when annotation placement is 'top', get the final entry in the `note.Ys()`, since that will have the (numerically lowest, screen highest) Y value.  Previously, it was always getting entry [0] which is the numerically highest, staff-lowest pitch.
old:
new test case:
I am upgrading my Ubuntu VM right now so I can't do visual diff.  But this will only affect cases with multiple pitch keys and stem up, and we didn't have any test cases for that.
> issue 1469 - get top Y for top annotation

- src/font.ts
- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/leland_metrics.ts
- src/fonts/petaluma_metrics.ts
- src/stringnumber.ts
In order to facilitate the review of #1486 this PR includes only the changes related to `StringNumber`:
- definition of `StringNumberMetrics`
- movement of these  metrics outside the `glyphs` section.
It is a step to address #1485
> Refactor FontMetrics: stringnumber

- src/chordsymbol.ts
- src/font.ts
- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/leland_metrics.ts
- src/fonts/petaluma_metrics.ts
In order to facilitate the review of #1486 this PR includes only the changes related to `ChordSymbol`:
- definition of `ChordSymbolMetrics`
- movement of these  metrics outside the `glyphs` section.
It is a step to address #1485
> Refactor FontMetrics: chordsymbol

- src/element.ts
- src/formatter.ts
- src/glyphnote.ts
- src/modifiercontext.ts
- src/tickable.ts
- src/util.ts
- src/voice.ts
Clarify a few points of the documentation/interfaces that were unclear to me.  Putting these in while trying to get a better handle on the formatter.
One refactor:  take sumArray from formatter.ts and put it in utils to use it in expTicksUsed calculations.
One bug fixed: setSoftmaxFactor() on voice was not resetting expTicksUsed()  [only a problem if a voice had its tickables added, then formatted, then setSoftmaxFactor(), then formatted again.]
> A few doc clarifications

- src/fonts/bravura_metrics.ts
- src/fonts/leland_metrics.ts
- src/note.ts
- src/stavemodifier.ts
- src/timesigglyph.ts
- src/timesignature.ts
- src/timesignote.ts
- tests/timesignature_tests.ts
To the extent possible without breaking backwards compatibility of public interfaces, this PR implements a little bit of my (second) comment on #1498 which @sschmidTU gave a thumbs up to: deemphasizing using structs in favor of objects themselves on TimeSignature and TimeSigNote.
Places line, glyph, num (now "is_numeric") attributes directly on the TimeSignature object (where the crucial .point) already is, rather than on a .info interface.   (Note that the name of this struct differs among modifiers.  On the Clef object it is ".clef", so changing one type of Modifier without changing all should not break code expecting a standard .info struct.)
TimeSigNote now stores the reference to the TimeSignature object rather than the .info struct, so that it can be modified up until the point it …
> Time Signature simplifications

- src/svgcontext.ts
- tests/notehead_tests.ts
fix #1126 
@ronyeh do these changes address the issue? There are no visual differences.
> fix scale calculation

- src/tables.ts
- tests/formatter_tests.ts
This PR has two commits:
- The first one changes the softmax formatter tests to use values between 1 and 15
- The second one changes the default to 10 (closest value to 8 used in the tests)
> softmax range in tests changed to 1 .. 15, softmax default to 10

- tests/bach_tests.ts
The only difference is in measure 8.
> Addresses a grace note issue mentioned in the #441 thread.

- src/notehead.ts
- src/stavenote.ts
- tests/notehead_tests.ts
fixes #556
- noteheads of stavenotes are not preformatted.
- stavenot reset should use setstave to recalculate properly.
> fix notehead bounding box

- src/fonts/common_metrics.ts
- src/multimeasurerest.ts
- src/textdynamics.ts
No visual differences on this one.
> point fixed on MultiMeasureRest and TextDynamics

- src/fonts/common_metrics.ts
- src/pedalmarking.ts
Two other point values fixed. Pedal glyph location now calculated in run time.
> point fixed on pedals

- src/fonts/common_metrics.ts
- src/note.ts
- src/parenthesis.ts
- src/tremolo.ts
- tests/percussion_tests.ts
No visual differences on Paranthesis. Tremolos are now bigger.
> point fixed on tremolo and parenthesis

- src/clef.ts
- src/fonts/common_metrics.ts
Four more points removed from the metrics. I have also used the same scale related to the size of the clef.
> clef annotations size refactor

- src/flow.ts
In order to adjust metrics the library has to provide access to the font stack.
> access to font stack

- src/fonts/common_metrics.ts
- src/staverepetition.ts
the point used with coda was 20, now making it standard to 39 they look much bigger but they follow now the creators' design.
> coda point standard

- src/canvascontext.ts
It's mainly useful in context of rendering in web worker, because web worker doesn't have access to devicePixelRatio, so resize code will be split between
1. main thread asking for a render, providing devicePixelRatio
2. Worker rendering and resizing CanvasContext w/ provided ratio
3. Worker giving back main thread the resize target
4. Main thread applying css width/height provided by the worker
> feat(CanvasContext): Added optional devicePixelRatio argument to resize

- package.json
- tests/flow.html
- tests/qunit/qunit.css
- tests/qunit/qunit.js
This fixes #1570 and #1571 
The newest version of QUnit was limiting the dropdown to the first 20 modules. We have way more modules....
```js
diff --git a/tests/qunit/qunit.css b/tests/qunit/qunit.css
index d445a567..5d8b3964 100644
--- a/tests/qunit/qunit.css
+++ b/tests/qunit/qunit.css
@@ -236,6 +236,9 @@
color: #0D3349;
background-color: #F5F5F5;
z-index: 99;
+
+    max-height: 80vh;
+    overflow: auto;
}
#qunit-modulefilter-actions {
diff --git a/tests/qunit/qunit.js b/tests/qunit/qunit.js
index 5e48b793..a01121e1 100644
--- a/tests/qunit/qunit.js
+++ b/tests/qunit/qunit.js
@@ -5509,7 +5509,7 @@
// module names, indicating how the interface works. This also makes
// for a quicker interaction in the common case of small projects.
// Don't mandate typing just to get the menu.
- …
```
> Qunit Fixes/Improvements

- tests/flow-headless-browser.html
- tests/flow.html
- tests/vexflow_test_helpers.ts
- tools/generate_images_pptr.js
- tools/generate_png_images.js
Hi Ron, please look into that, I had to undo some of your chenges in flow.html.
This PR avoids that the tests scroll behind the header.
> fix test scroll

- tools/get_releases.mjs
This patch allows for easier visual diffing between our current work and a release that has been published on NPM.
This was previously applied to the VexFlow 5+ repo: https://github.com/vexflow/vexflow/pull/8
> The grunt get:releases:X.Y.Z script fails because `npm pack` does not create the directory for you if it doesn't already exist.

- src/tables.ts
Fixes https://github.com/0xfe/vexflow/issues/1595. -0 seems to cause issues on certain platforms/environments. There are other instances where -0 is possible throughout the codebase, but I wanted this PR to be as minimal as possible.
> Prevent octave from being -0 when calculating key properties

- src/ornament.ts
- tests/ornament_tests.ts
When building a TickContext with multiple voices, such as a grand staff, the order of ticks was not continuous, so detection of the end of voice element failed and the Ornament display position was incorrect.
**Before**
**After**
> Fix ornament delayed draw, such as on a grand staff.

- src/stave.ts
- tests/keysignature_tests.ts
Prior to this fix, there was no way to show a key signature correctly in a bass clef stave, without the clef glyph (and any other non-treble).  I added a test case and created a `stave.addClefLines(clefSpec: string)` method that adds the logical clef (e.g. the lines match the clef) but without the glyph.
> issue #1603 - key signature on non-treble stave, no glyph

- src/barnote.ts
- tests/barline_tests.ts
BarNote is not opening its own context group which means it fails to perform operations requiring the id of the Element such as getSVGElement, addClass, removeClass etc.
I also added barline as a property of barnote to memoize it and have direct access to the barline if one needs it.
It looks like there are not any tests for the barnote directly but I added a test for the error scenario I was running into where  getSVGElement was always returning undefined for rendered BarNotes
> fix: BarNote getSVGElement always returning undefined

- Gruntfile.js
This fixes https://github.com/0xfe/vexflow/issues/1632
It addresses the confusion discussed in issue https://github.com/0xfe/vexflow/issues/1630
> Remove v3.0.9 from future bundles published to NPM.

- src/tables.ts
Remove part of a line in tables.ts that will never be executed -- raises a compiler error in Typescript 5.6 and above.  Probably a result of a refactor.  Will commit also to VF5 repo.
> Always truthy error
