- src/tuning.js
- tests/tuning_tests.js
Wanted to be able to create accurate banjo tabs with strings=5, so I added a tuning for the standard bluegrass banjo (DGBDg).
> Initial commit for standard banjo tuning (DGBDg)

- src/stave.js
Allows the x position of a stave to be changed.
> adds a setX method to stave

- src/keysignature.js
- src/tuplet.js
fixes https://github.com/0xfe/vexflow/issues/335
> KeySignature.cancelKey - Check if accList[0] exists before accessing it

- Gruntfile.js
> Use `rollup` task with `grunt watch`

- .eslintrc.json
- Gruntfile.js
- src/clef.js
- src/stave.js
- src/staveconnector.js
- src/stringnumber.js
- src/tuning.js
- src/vibrato.js
> Lint: clef, stave, staveconnector,  stringnumber,  tuning, vibrato

- Gruntfile.js
- src/annotation.js
- src/articulation.js
- src/barnote.js
- src/beam.js
- src/bend.js
Fix eslint errors for files listed in title.
> Lint: annotation, articulation, barnote, beam, bend

- src/factory.js
- tests/tuplet_tests.js
- tests/vexflow_test_helpers.js
> Refactor tuplet tests with factory

- src/factory.js
- tests/gracenote_tests.js
Added `GraceNote` and `GraceNoteGroup` to the `Factory`.
> Refactor grace note tests with factory

- src/formatter.js
- tests/accidental_tests.js
Added a `paddingBetween` option to `Formatter.SimpleFormat`
Some diffs will be significantly different due to scale/dimensions changing, but the notation itself has not been changed (as far as I could tell).
> Refactor accidental tests with factory

- src/vex.js
- tests/stavenote_tests.js
> Reformat and refactor stavenote tests

- tests/auto_beam_formatting_tests.js
~~WIP don't merge.~~
EDIT: 
Good to go. 
Removed all clefs since beaming is clef agnostic.
> Refactor auto-beaming tests to use EasyScore.

- src/annotation.js
- src/factory.js
- src/frethandfinger.js
- src/modifier.js
- src/staveconnector.js
- tests/bach_tests.js
- tests/run.js
This is a test to flesh out the `System`, `EasyScore` and `Factory` APIs. I hope to put the entire first part of the piece here. This will also be useful as a regression test when its done.
Current progress:
Open issues:
* Lots of duplication in building systems. `System` should support `measures` parameter so creating multi-measure systems is easy.
* Time signature is not vertically centered.
* Registry and IDs are super helpful. Adding classes to `EasyScore` keyvals will be enormously helpful configuring multiple similar notes.
* `EasyScore` keyvals for Articulations and Annotations may be helpful.
* ~~`StaveConnector` types need `Factory` shortcuts (like position and justification)~~
* Factory should register elements created by it instead of default registry.
> WIP: Render first 32 measures of Bach Minuet

- src/curve.js
- src/easyscore.js
- src/factory.js
- src/system.js
- tests/bach_tests.js
Along with more fleshing out of classes (and some refactoring to reduce duplication.)
Demo (click for full size):
> Bach Minuet, PR 2, 18 Measures

- src/factory.js
- src/pedalmarking.js
- src/stavehairpin.js
- src/tables.js
- src/tickcontext.js
- tests/pedalmarking_tests.js
This is good to go. Diffs are due to staves shifting position.
I noticed that all the tests were using the exact same setup, so I isolated the only thing that changes: the construction of the pedal marking.
> Refactor pedal marking tests

- src/factory.js
- src/tabnote.js
- tests/beam_tests.js
This is nearly done.
But for some reason **Outlier Beam** is looking weird -- notice the beam slopes:
Haven't figured out why yet.
> Refactor beam tests

- tests/curve_tests.js
Diffs will be due to stave position/size changes
> Refactor Curve tests

- src/factory.js
- tests/textnote_tests.js
Diffs due to staves changing position/size.
> Refactor TextNote tests

- src/factory.js
- tests/ghostnote_tests.js
* Added `GhostNote` to `Factory`
* Added a `.getVoices` method to `Factory` so that the created voices can be accessed.
* Continuing with the `createTest` pattern I've been refining over the past few PRs
> Refactor GhostNote tests

- tests/curve_tests.js
* Moved `createTest` out of object
* Alias `VF.Test.runTests` to `run`
> Make Curve tests more consistent with recent test pattern

- tests/voice_tests.js
Basically just linting, and making sure the stave is set early.
> Lint voices_test.js; slight refactor of "Full Voice Mode" test

- tests/percussion_tests.js
> Refactor percussion tests

- tests/stavehairpin_tests.js
> Refactor StaveHairpin tests

- src/factory.js
- tests/staveline_tests.js
> Add StaveLine to Factory; Refactor StaveLine tests

- src/factory.js
- tests/notesubgroup_tests.js
> Add NoteSubGroup and TimeSigNote to Factory; Refactor NoteSubGroup tests

- src/stavenote.js
- tests/formatter_tests.js
In the process of refactoring the Formatter tests I discovered a bug, that the `StaveNote.extraLeftPx` and `StateNote.extraRightPx` properties were not being re-calculated when the `NoteHeads` get rebuilt in `StaveNote#reset`. Quite a few diffs are related to this fix.
> Fix stem-down displaced notehead bug; refactor Formatter tests

- tests/timesignature_tests.js
> Refactor TimeSignature tests

- tests/rests_tests.js
I admittedly didn't do much here in terms of structure... mainly reformatted. Although a lot of these tests had redundant renders which made the output bolder than expected (the diffs make this obvious.
But the `multi` test is the final test that needed restructuring to avoid use of the `voice.draw(ctx, stave)` pattern
> Refactor Rests tests

- src/barnote.js
- src/factory.js
- src/stavebarline.js
- tests/barline_tests.js
> Add BarNote to Factory; Refactor barline_tests.js

- src/factory.js
- src/stringnumber.js
- tests/stringnumber_tests.js
> Add StringNumber to Factory; refactor StringNumber tests

- tests/dot_tests.js
> Refactor Dot tests

- src/tuplet.js
- tests/tuplet_tests.js
Add support for single-note tuplets. Fixes issue #548
> One note tuplets

- src/index.js
fix warning introduced by #683
> fix double quote lint warning

- src/svgcontext.js
> bugfix(svgcontext.js): restore scale on resize & state save/restore

- Gruntfile.js
#794 Map file not generated for debug build
> generate map file in debug mode

- tests/accidental_tests.js
- tests/formatter_tests.js
Exhibit some problems with current formatter.  The first case is not really with the formatter, but I needed the accidental padding to be correct to test other alignment issues.
> add some formatter test cases

- src/element.ts
- src/types/common.d.ts
Comments included, types relocated.
> Migration2/element 

- src/stemmablenote.ts
Migration visual issues resolved. @0xfe you were right a proble with `getYForTopText` but in `StemmableNote`
> fix getYForTopText

- src/multimeasurerest.ts
- src/timesignature.ts
> multimeasurerest fix

- src/multimeasurerest.ts
- src/timesignature.ts
- src/timesignote.ts
> getTimeSig to getInfo, TimeSignature.timeSig to TimeSignature.info

- tests/annotation_tests.js
- tests/articulation_tests.js
- tests/formatter_tests.js
- tests/gracetabnote_tests.js
- tests/rests_tests.js
- tests/tabnote_tests.js
- tests/tabslide_tests.js
- tests/tabtie_tests.js
- tests/tickcontext_tests.js
- tests/voice_tests.js
VF.Test.TIME4_4 is now undefined due to our TypeScript migration.
`npm run test:reference` results in 0 diffs from current master.
> Replace VF.Test.TIME4_4 with VF.TIME4_4.

- src/accidental.ts
- src/annotation.ts
- src/articulation.ts
- src/barnote.ts
- src/beam.ts
- src/bend.ts
- src/boundingbox.ts
- src/modifier.ts
- src/music.ts
- src/tables.ts
- src/tremolo.ts
- src/util.ts
Accidental, Annotation, Articulation, util, ...
> documentation update

- src/stave.ts
- src/stavenote.ts
Addresses #729.
setLedgerLineStyle sets the ledger line style of all the stave notes in the system.
> setLedgerLineStyle in Stave

- src/easyscore.ts
- src/factory.ts
- src/stave.ts
- src/system.ts
@0xfe @ronyeh I am trying to render Claire de Lune, documenting the Easy Score API on the way. I did not get too far and I suggest to use this PR to discuss and progress on the documentation.
> Api Documentation: easyscore

- CHANGELOG.md
I am breaking up the larger PR https://github.com/0xfe/vexflow/pull/1094 into smaller pieces that are easier to review & merge. :-)
The larger PR will be rebased off of master as needed.
> Add a CHANGELOG.md to track breaking changes and new features.

- src/easyscore.ts
- src/system.ts
`System.format` is misiing the update of `this.boundingBox`
> System.format not calculating this.boundingBox

- src/util.ts
- tests/keysignature_tests.ts
- tests/music_tests.ts
- tests/tabnote_tests.ts
- tests/tuning_tests.ts
- tests/voice_tests.ts
Fixes https://github.com/0xfe/vexflow/issues/1130
> Replace try / catch blocks in tests with the QUnit throws() assertion.

- src/easyscore.ts
- tests/bach_tests.ts
- tests/formatter_tests.ts
- tests/ghostnote_tests.ts
- tests/strokes_tests.ts
- tests/textnote_tests.ts
- tests/threevoice_tests.ts
`TODO: EasyScore ...` resolved.
> EasyScore.voice accepts Note

- src/stave.ts
- tests/stave_tests.ts
- tests/stavemodifier_tests.ts
- tests/tabstave_tests.ts
> Remove drawVertical from Stave

- src/accidental.ts
- src/articulation.ts
- src/clef.ts
- src/keysignature.ts
- src/timesignature.ts
- tests/tabstave_tests.ts
> fix #1124 !this.x

- tests/boundingboxcomputation_tests.ts
Fixes #1162 resolving TODO in test file.
> fix #1162 duplicate image filename

- src/accidental.ts
- tests/accidental_tests.ts
> fix #1169 applyAccidentals

- tests/run.ts
- tests/tremolo_tests.ts
Test added to check if #555 was still an issue.
It is fine with Bravura but it is not right with the other fonts.
@AaronDavidNewman any idea?
> tremolo tests added

- src/textnote.ts
Minor typo in documentation fixed.
@mscuthbert thanks for the hint!
> SetStave typo fixed

- src/canvascontext.ts
Rename vexFlowCanvasContext to context2D and other smaller fixes. For example, I lowercased the first letter of `sanitizeCanvasDims()`. This should be safe, since it's only used internally by this class. (It's basically a private helper function.)
Following Rodrigo's advice, I'm extracting some of the smaller changes out of my [Font mega-PR](https://github.com/0xfe/vexflow/pull/1163).
Apologies if the diff looks big. I moved the font accessors to the bottom of the file so that it is closer to the version in the Font PR.
Ran the tests. No visual diffs.
> Rename vexFlowCanvasContext to context2D.

- src/flow.ts
Add some symbols to flow.ts that were previously available in Tables.ts
> add some missing exports

- src/accidental.ts
- src/articulation.ts
- src/barnote.ts
- src/beam.ts
- src/clef.ts
- src/crescendo.ts
- src/easyscore.ts
- src/font.ts
- src/formatter.ts
- src/gracenotegroup.ts
- src/gracetabnote.ts
- src/modifiercontext.ts
- src/note.ts
- src/ornament.ts
- src/repeatnote.ts
- src/stavemodifier.ts
- src/stem.ts
- src/stemmablenote.ts
- src/tables.ts
- src/textdynamics.ts
- src/timesignature.ts
- src/tremolo.ts
- src/tuplet.ts
- src/typeguard.ts
- src/vex.ts
- src/vibratobracket.ts
- tests/articulation_tests.ts
- tests/style_tests.ts
- tests/tabnote_tests.ts
This PR also contributes to the reduction of Font mega PR #1163. 
- Minor fixes 
- Defines `Tables.currentMusicFont()`
- Defines `Font.SANS_SERIF`
- Defines `Font.SERIF`
All changes attributable to @ronyeh, thanks Ron!
> Minor changes

- package-lock.json
- package.json
- src/canvascontext.ts
- tests/offscreencanvas_tests.ts
- tests/run.ts
> Offscreen canvas

- tests/formatter/tests.js
matched addModifier parameter order of tests/formatter/tests.js
is this ok? @rvilarl
> matched addModifier parameter order of formatter test

- Gruntfile.js
> adjust puppeteer options for linux

- Gruntfile.js
- package-lock.json
- package.json
- patches/parse-path+4.0.3.patch
- skip an unnecessary git commit during the release process
- patch an issue in the parse-path npm package so we can release to the correct repo https://github.com/IonicaBizau/parse-path/pull/32
- small clean up
> Gruntfile.js improvements

- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/petaluma_metrics.ts
- src/frethandfinger.ts
- src/stringnumber.ts
- tests/formatter_tests.ts
Prettier automatic corrections. No visual changes.
> prettier changes

- Gruntfile.js
- package-lock.json
- package.json
- tests/flow.html
- tools/generate_png_images.js
- tools/visual_regression.sh
Fixes: https://github.com/0xfe/vexflow/issues/1318
Also adds a small tweak to flow.html which allows it to run directly from unpkg.com.
> Improve release script.

- Gruntfile.js
- tools/version_info.js
Fix the release script:
* Do not assume that the typescript compiler `tsc` is installed globally.
* Patch the buggy `parse-path` package before release-it is imported via `require()`.
> Release script

- src/formatter.ts
- tests/formatter_tests.ts
> Address bug 1335, right padding for longer last note in measure

- src/beam.ts
Just for fixing the issue https://github.com/0xfe/vexflow/issues/1374
> Fix render beam without steam rendering

- src/gracenotegroup.ts
fixes #1363
Visual differences (bravura in order diff, current, reference), notes with grace notes move two pixels to the right.
> add left padding to gracenote group

- src/stavenote.ts
- tests/accidental_tests.ts
Fixes #104 
This addresses the problem once discussed in #104.
I decided to go an implement option 2. 
No visual differences.
> chords no longer need to be sorted

- demos/fonts/core-with-promise.html
- demos/fonts/core.html
- demos/fonts/leland.html
- entry/vexflow-core.ts
- src/fonts/load_leland.ts
* FIX entry/vexflow-core.ts by adding Leland font module mapping.
* ADD demos for Leland font.
* REMOVE unnecessary comments from load_leland.ts, which already exist in
load_bravura.ts.
> Small fixes for Leland PR

- src/formatter.ts
> document need to call joinVoices

- src/rendercontext.ts
- src/svgcontext.ts
- src/tuplet.ts
> fix colon in tuplets and dot in debug bars

- src/element.ts
Fixes #1443 
On the first step to address #285 I have made `Element.attrs` and `Registry` consistent. Both accept `string | undefined`
- `Element.attrs.class` is now a string with a space joined array of class names.
> Refactor & dynamic styling (step 1 Element.attrs as map of strings)

- src/beam.ts
- src/chordsymbol.ts
- src/clef.ts
- src/glyphnote.ts
- src/keysignature.ts
- src/notehead.ts
- src/ornament.ts
- src/stave.ts
- src/stavebarline.ts
- src/stavenote.ts
- src/stavetie.ts
- src/stem.ts
- src/tabnote.ts
- src/timesignature.ts
Make the combination openGorup/applyStyle closeGroup/restoreStyle in the code set
> fix applyStyle calls location

- src/svgcontext.ts
fixes #1451
fixes #596
I'm verry proud of this PR, hope you like it. I have followed the approach:
> 3) Where possible, when a group is open, apply attributes to the group element instead of its children.
_Originally posted by @gristow in https://github.com/0xfe/vexflow/issues/596#issuecomment-386156535_
There is no visual differences and the size of the SVGs have been reduced by 5,2MB
> styles refactored to consider groups

- src/stavetempo.ts
> Make stavetempo use text formatter and not getBBox

- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/leland_metrics.ts
- src/fonts/petaluma_metrics.ts
- src/notehead.ts
fixes #1415 
location is now calculated on run time and the associated metrics are no longer required.
> custom noteheads refactored

- src/annotation.ts
- src/articulation.ts
- src/beam.ts
- src/chordsymbol.ts
- src/clefnote.ts
- src/dot.ts
- src/formatter.ts
- src/glyph.ts
- src/glyphnote.ts
- src/gracenote.ts
- src/multimeasurerest.ts
- src/note.ts
- src/notehead.ts
- src/repeatnote.ts
- src/staveline.ts
- src/stavenote.ts
- src/stavetempo.ts
- src/stemmablenote.ts
- src/tables.ts
- src/tabnote.ts
- src/textbracket.ts
- src/textnote.ts
- src/tuning.ts
- tests/rests_tests.ts
Time to try that again.
continued from #1420
> refactor any in GlyphProps

- tools/compare/README.md
- tools/compare/compare.js
- tools/compare/index.html
- tools/compare/styles.css
Add query params to the compare tool. For example, open the following in a local browser:
`vexflow/tools/compare/index.html?currentLabel=PR-1480&referenceLabel=4.1.0`
Try out this URL: `file:///PATH_TO_VEXFLOW/tools/compare/index.html?currentLabel=PR-1480&referenceLabel=4.1.0#`
This is to help with reviewing output images, for example PR #1480
> Improve compare tool with more UI improvements to help with generating GIFs for reviewing PRs.

- src/annotation.ts
- src/chordsymbol.ts
- src/clef.ts
- src/clefnote.ts
- src/font.ts
- src/fonts/bravura_metrics.ts
- src/fonts/gonville_metrics.ts
- src/fonts/leland_metrics.ts
- src/fonts/petaluma_metrics.ts
- src/notehead.ts
- src/ornament.ts
- src/stavenote.ts
- src/strokes.ts
- src/tuplet.ts
> Refactor FontMetrics

- tools/generate_images.js
> Image generation: set pptr as default

- .github/workflows/ci-workflow.yaml
- package.json
`CI` is ___always___ defined in GitHub Actions.
* https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
> Update GitHub Actions

- src/accidental.ts
- src/articulation.ts
- src/clef.ts
- src/clefnote.ts
- src/fonts/common_metrics.ts
- src/fonts/gonville_metrics.ts
- src/keysignature.ts
- src/ornament.ts
- src/stavetempo.ts
- src/strokes.ts
- src/timesigglyph.ts
- src/timesignature.ts
fixes #1527 
Default 39
Small two-thirds (26)
As shown in #1527 the sizes are now better and the complexity of the common metrics is reduced.
> point fixed on time signatures and clefs

- src/fonts/common_metrics.ts
- src/textnote.ts
> point fixed on ornaments and text notes

- src/fonts/common_metrics.ts
Rest use now default point size
> point fixed on rests

- src/stavenote.ts
- src/tables.ts
- tests/index.ts
- tests/unison_tests.ts
fixes #1507 
No visual differences with `Tables.UNISON=true` which is the default value.
> unison configurable

- src/fonts/common_metrics.ts
- src/tuplet.ts
tupletPoint now calculated at runtime
> tuplet point refactored
